id = "eden"
name = "Eden"
[capabilities]
launch = true
settings = true
[platforms]
supported = ["switch"]
[config]
strategy = "direct"
directory = "config"
[launch.standalone]
command = "/usr/bin/eden"
controller_mode = "compat"
[launch.game]
command = "/usr/bin/eden"
