id = "retroarch"
name = "RetroArch"
[capabilities]
launch = true
settings = true
[platforms]
supported = ["nes", "genesis"]
[config]
strategy = "direct"
directory = "config"
[launch.standalone]
command = "/usr/bin/retroarch --menu"
controller_mode = "game"
[launch.game]
command = "/usr/bin/retroarch"
