import unittest
from pathlib import Path


ROOT = Path(__file__).parents[1]
QML = (ROOT / "ui" / "ConsoleShell.qml").read_text()
SHELL_PROFILE = (ROOT / "config" / "inputplumber" / "profiles" / "shell.yaml").read_text()


class ConsoleUiTests(unittest.TestCase):
    def test_qml_preserves_card_to_space_shell_interaction(self) -> None:
        self.assertIn('property var domains: ["System", "Store", "Library", "Recent"]', QML)
        self.assertIn("property int selectedCategoryIndex: 3", QML)
        self.assertIn('property string space: "home"', QML)
        self.assertIn('presentationTarget = "library"', QML)
        self.assertIn('root.space = root.presentationTarget', QML)
        self.assertIn('space = "home"', QML)
        self.assertIn('readonly property string apiUrl:', QML)
        self.assertIn("function activate()", QML)
        self.assertIn("property bool launchOverlayEnabled: controllerBridge.launchOverlayEnabled === true", QML)
        self.assertIn("readonly property bool launchOverlayEffectiveVisible:", QML)
        self.assertIn("visible: root.launchOverlayEffectiveVisible", QML)
        self.assertIn("function moveDomain(delta)", QML)
        self.assertIn("function openSteamStore()", QML)
        self.assertIn('message = "System space is not implemented"', QML)
        self.assertIn('function openGameOptions(game)', QML)
        self.assertIn('event.key === Qt.Key_X', QML)
        self.assertIn('action: "options"', QML)
        self.assertIn('GameOptions {', QML)
        self.assertIn('space === "library" && libraryFocus === "games"', QML)
        self.assertIn('space === "home" && selectedCategoryIndex === 3', QML)
        self.assertIn('if (gameOptionsView === "menu")', QML)
        self.assertIn("Math.max(0, Math.min(domains.length - 1", QML)
        self.assertIn("Math.max(0, Math.min(recentHome.itemCount - 1", QML)
        self.assertNotIn("% domains.length", QML)
        self.assertNotIn("% catalogueRecentModel.count", QML)
        self.assertNotIn("Behavior on opacity", QML)
        self.assertNotIn("Behavior on scale", QML)
        recent = (ROOT / "ui" / "RecentHome.qml").read_text()
        self.assertIn("toRelativeIndex: index - recentHome.selectedIndex", recent)
        self.assertNotIn("visibleRailRadius", recent)
        self.assertNotIn("presentationStartVisible", recent)
        self.assertIn("capturePresentation()", recent)
        self.assertIn("suppressTransitionCompletion", recent)
        self.assertIn("transitionAnimation.stop()", recent)
        self.assertIn("transitionAnimation.start()", recent)
        self.assertIn("compactCardWidth + railGap", recent)
        self.assertNotIn("edgeViewportWidth", recent)
        self.assertNotIn("edgePeek", recent)
        self.assertIn("x: -root.homeContentRailX", QML)
        self.assertIn("titleRailY", QML)
        self.assertIn("titleRailTargetY", QML)
        self.assertIn("titleRailActiveGap", QML)
        self.assertIn("titleRailLayoutY(index, activeIndex)", QML)
        self.assertIn("visible: true", QML)
        self.assertIn("anchors.horizontalCenter: parent.horizontalCenter", QML)
        self.assertIn("homeBottomBandCenterY: height - design(36)", QML)
        self.assertIn("homeCategoryRailX: design(52)", QML)
        self.assertIn('homeCategoryFontSize: typography.size("display", 48)', QML)
        self.assertIn("homeCategoryGap: design(25)", QML)
        self.assertIn("homeCategoryPitch: homeCategoryFontSize + homeCategoryGap", QML)
        self.assertNotIn('text: "HOME"', QML)
        self.assertIn("homeFocalCardHeight", QML)
        self.assertIn("homeFocalCardWidth", QML)
        self.assertIn("homeCompactCardWidth", QML)
        self.assertIn("homeNavigationCardAspect: 0.62", QML)
        self.assertIn("homeNavigationCardHeight: homeNavigationCardWidth", QML)
        self.assertIn("compactCardWidth: homeNavigationCardWidth", QML)
        self.assertIn("compactCardHeight: homeNavigationCardHeight", QML)
        self.assertIn("compactGameCardWidth: compactCardWidth", QML)
        self.assertIn("homeCategoryTitleSelectedProgress", QML)
        self.assertIn("homeCategoryTitleOpacityForSelection", QML)
        self.assertIn("Math.abs(index - selectedIndex)", QML)
        self.assertIn("var minimumOpacity = 0.30", QML)
        self.assertIn("var maximumDistance = 3.0", QML)
        self.assertIn("(1.0 - minimumOpacity) / maximumDistance", QML)
        self.assertIn("luluPalette.navigationText", QML)
        self.assertIn("luluPalette.headingAccent", QML)
        self.assertIn("homeInterCardGap: design(24)", QML)
        self.assertIn("homeHeadingCardClearance: design(12)", QML)
        self.assertIn("homeCompositionOffsetY: -design(36)", QML)
        self.assertIn("opacity: libraryHome.contentOpacity", (ROOT / "ui" / "LibraryHome.qml").read_text())
        self.assertIn("property bool libraryHandoffPending: false", QML)
        self.assertIn("handoffTimer.restart()", QML)
        self.assertIn("NavigationCard", (ROOT / "ui" / "LibraryHome.qml").read_text())
        self.assertIn('request("/?scope=recent"', QML)
        self.assertIn('readonly property string libraryScope:', QML)
        self.assertNotIn("/dev/input", QML)
        self.assertNotIn("Social", QML)

    def test_reset_mudos_uses_the_shared_session_boundary(self) -> None:
        guide = (ROOT / "ui" / "MudosGuide.qml").read_text()
        system_space = (ROOT / "ui" / "SystemSpace.qml").read_text()
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        native_guide = (ROOT / "native" / "mudos-guide.cpp").read_text()
        self.assertIn('guideModel.actions', guide)
        self.assertIn('GetGuideActions', native_guide)
        base = (ROOT / "config/guide/base.toml").read_text()
        self.assertIn('id = "switch-compatibility"', base)
        self.assertIn('id = "restart-mudos"', base)
        self.assertIn('id = "reboot-system"', base)
        self.assertIn('id = "shutdown-system"', base)
        self.assertIn('ExecuteGuideAction', native_guide)
        self.assertIn('key === "lulu.reset"', system_space + QML)
        self.assertIn('request("/reset", "POST"', QML)
        self.assertIn("call_reset_mudos", bridge)
        self.assertIn('path == "/reset"', bridge)

    def test_shell_guide_is_limited_and_confirms_power_actions_natively(self) -> None:
        guide = (ROOT / "ui" / "MudosGuide.qml").read_text()
        native_guide = (ROOT / "native" / "mudos-guide.cpp").read_text()
        native_shell = (ROOT / "native" / "lulu-shell.cpp").read_text()
        self.assertIn('guideModel.actions', guide)
        self.assertIn('confirm', native_guide)
        self.assertIn('viewModel_->value("confirmationPending").toBool()', native_guide)
        self.assertIn('target = "system:reboot"', (ROOT / "config/guide/base.toml").read_text())
        self.assertIn('target = "system:shutdown"', (ROOT / "config/guide/base.toml").read_text())
        self.assertNotIn('Quit Application', guide)
        self.assertNotIn('systemctl', guide)
        self.assertNotIn('focusedWindow_ == window_->winId()', native_shell)

    def test_retroarch_provider_menu_fallback_is_native_and_platform_scoped(self) -> None:
        native_guide = (ROOT / "native" / "mudos-guide.cpp").read_text()
        retroarch = (ROOT / "config/providers/retroarch/provider.toml").read_text()
        pcsx2 = (ROOT / "config/providers/pcsx2/provider.toml").read_text()
        self.assertIn('target = "command:/usr/bin/retroarch --command MENU_TOGGLE"', retroarch)
        self.assertIn('target = "key:F12"', pcsx2)
        self.assertIn('xcb_test_fake_input', native_guide)
        self.assertIn('XK_F12', native_guide)

    def test_extracted_ui_primitives_preserve_real_game_card_data(self) -> None:
        for filename in ("GameCard.qml", "RecentHome.qml", "LibraryHome.qml", "LibrarySpace.qml", "PlaceholderHome.qml"):
            self.assertTrue((ROOT / "ui" / filename).exists())
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertIn("property var game: null", game_card)
        self.assertIn("card.game.artwork_url", game_card)
        self.assertIn("signal collectionChanged", library_space)
        self.assertIn("signal launchRequested", library_space)

    def test_recent_refresh_avoids_unchanged_model_replacement(self) -> None:
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        navigation_surface = (ROOT / "ui" / "NavigationCardSurface.qml").read_text()
        spatial_surface = (ROOT / "ui" / "LibrarySpatialSurface.qml").read_text()
        self.assertNotIn("interval: 16", navigation_surface + spatial_surface)
        self.assertIn("readonly property var catalogueRecentModel: recentModel", QML)
        self.assertIn("recentModel: root.catalogueRecentModel", QML)
        self.assertNotIn("recentGames =", QML)
        self.assertIn("property string selectionAnchorId", (ROOT / "ui" / "RecentHome.qml").read_text())
        self.assertNotIn("recentModel.count", (ROOT / "ui" / "RecentHome.qml").read_text())
        self.assertIn("recentRepeater.count", (ROOT / "ui" / "RecentHome.qml").read_text())
        self.assertIn("nativePlayCanonicalRect", game_card)
        self.assertIn("canonicalRect: root.canonicalRect", navigation_surface)

    def test_recent_selection_has_one_live_index_derived_identity(self) -> None:
        recent = (ROOT / "ui" / "RecentHome.qml").read_text()
        self.assertIn("readonly property string selectedGameId:", recent)
        self.assertNotIn("selectedGameId =", recent)
        shell = QML
        self.assertIn("readonly property string recentSelectedGameId:", shell)
        self.assertNotIn("root.recentSelectedGameId =", shell)
        self.assertIn("beginPendingHomeLaunch(visibleRecentGame)", shell)

    def test_provider_and_download_guide_actions_are_contextual(self) -> None:
        guide = (ROOT / "ui" / "MudosGuide.qml").read_text()
        native = (ROOT / "native" / "mudos-guide.cpp").read_text()
        consoled = (ROOT / "src" / "lulu" / "consoled.py").read_text()
        self.assertIn('guideModel.actions', guide)
        self.assertIn('def GetGuideActions', consoled)
        self.assertIn('def SetProviderSetting', consoled)
        self.assertIn('load_providers()', consoled)
        self.assertNotIn('source: "UiAudioEngine.qml"', guide)
        self.assertNotIn("audioEventSerial", guide + native)
        self.assertNotIn("fps_show", guide + native)

    def test_controller_hint_groups_center_on_the_full_interaction_rail(self) -> None:
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        self.assertGreaterEqual(shell.count("width: implicitWidth"), 2)
        self.assertEqual(shell.count("anchors.horizontalCenter: parent.horizontalCenter"), 2)
        self.assertNotIn("width: parent.width * 0.54", shell)

    def test_internet_settings_uses_network_boundary_and_controller_model(self) -> None:
        qml = (ROOT / "ui" / "InternetSettings.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        consoled = (ROOT / "src" / "lulu" / "consoled.py").read_text()
        network = (ROOT / "src" / "lulu" / "network_manager.py").read_text()
        self.assertIn('signal operationRequested(string action, string ssid, string password)', qml)
        self.assertIn('operationRequested("connect", selectedSsid, password)', qml)
        self.assertIn('request("/network"', shell)
        self.assertIn('request("/keyboard/show"', shell)
        self.assertIn('path.startswith("/network/")', bridge)
        self.assertIn('def GetNetworkState', consoled)
        self.assertIn('def ConnectWifi', consoled)
        self.assertIn('BusType.SYSTEM', network)
        self.assertNotIn('nmcli', network)
        self.assertIn('operationRequested("forget", row.ssid, "")', qml)
        self.assertIn('passwordInput.forceActiveFocus()', qml)

    def test_audio_settings_uses_session_audio_boundary_and_controller_model(self) -> None:
        qml = (ROOT / "ui" / "AudioSettings.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        consoled = (ROOT / "src" / "lulu" / "consoled.py").read_text()
        audio = (ROOT / "src" / "lulu" / "audio_manager.py").read_text()
        self.assertIn('signal operationRequested(string action, string deviceId, int volume, bool inputDevice, bool muted)', qml)
        self.assertIn('Left/Right: Volume', qml)
        self.assertIn('request("/audio"', shell)
        self.assertIn('path.startswith("/audio/")', bridge)
        self.assertIn('def GetAudioState', consoled)
        self.assertIn('def SetAudioVolume', consoled)
        self.assertIn('pactl', audio)
        self.assertNotIn('QtMultimedia', qml + shell)

    def test_storage_settings_uses_udisks_boundary_and_stable_targets(self) -> None:
        qml = (ROOT / "ui" / "StorageSettings.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        consoled = (ROOT / "src" / "lulu" / "consoled.py").read_text()
        storage = (ROOT / "src" / "lulu" / "storage_manager.py").read_text()
        paths = (ROOT / "src" / "lulu" / "paths.py").read_text()
        self.assertIn('request("/storage"', shell)
        self.assertIn('path.startswith("/storage/")', bridge)
        self.assertIn('def GetStorageState', consoled)
        self.assertIn('def MountStorage', consoled)
        self.assertIn('BusType.SYSTEM', storage)
        self.assertIn('IdUUID', storage)
        self.assertIn('system', storage)
        self.assertIn('steam_library_root', paths)
        self.assertIn('request("/refresh"', shell)
        self.assertIn('root.refreshCatalogue()', shell)
        self.assertNotIn('lsblk', storage + qml)

    def test_typography_uses_central_semantic_families(self) -> None:
        typography = (ROOT / "ui" / "Typography.qml").read_text()
        self.assertIn("FontLoader", typography)
        self.assertIn("regularFont.name", typography)
        self.assertIn("iconFamily: bundledFamily", typography)
        self.assertIn("displayWeight: Font.Black", typography)
        self.assertIn("majorHeadingFamily: bundledFamily", typography)
        self.assertIn("majorHeadingWeight: Font.Black", typography)
        self.assertIn("interfaceFamily: bundledFamily", typography)
        palette = (ROOT / "ui" / "LuluPalette.qml").read_text()
        for role in ("guideSurface", "guideBorder", "guideItemSurface", "guideSelectedText",
                     "overlayBackdrop", "overlaySurface", "launchOverlaySurface"):
            self.assertIn(role, palette)
        self.assertIn("function size(role, value)", typography)
        for filename in ("ConsoleShell.qml", "GameCard.qml", "LibraryHome.qml", "LibrarySpace.qml", "PlaceholderHome.qml", "RecentHome.qml"):
            self.assertIn("typography", (ROOT / "ui" / filename).read_text())

    def test_semantic_asset_and_controller_boundaries(self) -> None:
        catalog = (ROOT / "ui" / "MudosAssetCatalog.js").read_text()
        profiles = (ROOT / "ui" / "ControllerProfiles.js").read_text()
        icon = (ROOT / "ui" / "MudosIcon.qml").read_text()
        controller = (ROOT / "ui" / "ControllerGlyph.qml").read_text()
        self.assertIn("wifi:", catalog)
        self.assertIn("function platformArtwork", catalog)
        self.assertIn("function suppliedArtwork", catalog)
        self.assertIn("function physicalControl", profiles)
        self.assertIn("function glyphFile", profiles)
        self.assertIn("function glyph(profile, action)", profiles)
        self.assertIn('confirm: "a"', profiles)
        self.assertIn('previousCollection: "leftBumper"', profiles)
        self.assertIn('a: "\\u0100"', profiles)
        self.assertIn('source: "fonts/Config-Glyphs.otf"', controller)
        self.assertIn('options: "x"', (ROOT / "ui" / "ControllerProfiles.js").read_text())
        self.assertIn("MudosAssetCatalog.icon", icon)
        self.assertNotIn('font.family: "JetBrains Mono"', controller)
        self.assertIn("controllerProfile", controller)

    def test_ui_palette_is_semantic_and_centralized(self) -> None:
        palette = (ROOT / "ui" / "LuluPalette.qml").read_text()
        for role in ("primaryText", "secondaryText", "mutedText", "selectedText", "accent",
                     "focusIndicator", "warning", "glassTint", "glassBorder", "backdrop"):
            self.assertIn("property color " + role, palette)
        for filename in ("ConsoleShell.qml", "GameCard.qml", "RecentHome.qml", "LibraryHome.qml", "LibrarySpace.qml", "PlaceholderHome.qml"):
            component = (ROOT / "ui" / filename).read_text()
            self.assertIn("luluPalette", component)
            self.assertNotRegex(component, r'(?m)^\s*(?:border\.)?color:\s*"#')

    def test_system_status_strip_is_shell_level_and_responsive(self) -> None:
        strip = (ROOT / "ui" / "SystemStatusStrip.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        native = (ROOT / "native" / "lulu-shell.cpp").read_text()
        self.assertIn('property bool compact', strip)
        self.assertIn('property var controllers', strip)
        self.assertIn('property int activeDownloadCount', strip)
        self.assertIn('visible: root.activeDownloadCount > 0', strip)
        self.assertIn('property string networkConnectionType', strip)
        self.assertIn('root.networkConnectionType === "ethernet"', strip)
        self.assertIn('String.fromCodePoint(0xF0201)', strip)
        self.assertIn('"\\uf1eb"', strip)
        self.assertIn('"\\uf6a9"', strip)
        self.assertIn('String.fromCodePoint(0xF00AF)', strip)
        self.assertIn('text: String(modelData.index === undefined ? "?" : modelData.index)', strip)
        self.assertIn('visible: modelData.batteryKind === "percent"', strip)
        self.assertIn('text: ": " + String(modelData.battery)', strip)
        self.assertNotIn('"Unknown" : modelData.battery', strip)
        self.assertIn('Qt.formatTime(new Date(), "HH:mm")', strip)
        self.assertIn('SystemStatusStrip {', shell)
        self.assertIn('systemStatus.networkConnected', shell)
        self.assertIn('systemStatus.bluetoothPowered', shell)
        self.assertIn('systemStatus.activeDownloadCount', shell)
        self.assertIn('systemStatus.networkConnectionType', shell)
        self.assertIn('org.lulu.Acquisitiond', native)
        self.assertIn('activeDownloadCountChanged', native)
        self.assertIn('acquisitionSnapshotChanged', native)
        self.assertIn('acquisitionAvailable', native)
        self.assertIn('onAcquisitionRegistered', native)
        self.assertIn('onAcquisitionUnregistered', native)
        self.assertIn('updateAcquisitionSnapshot(QStringLiteral("{\\"jobs\\":[],\\"activeDownloadCount\\":0}"), false)', native)
        self.assertIn('refreshAcquisitionStatus()', native)
        self.assertIn('acquisitionSnapshot', shell)
        self.assertIn('interval: 30000', shell)
        self.assertIn('controllers: controllerBridge.controllers', shell)
        self.assertNotIn('statusControllers', shell)
        self.assertIn('setContextProperty("systemStatus", &systemStatus)',
                      (ROOT / "native" / "lulu-shell.cpp").read_text())
        self.assertIn('Q_PROPERTY(QString bluetoothState', native)
        self.assertIn('Q_PROPERTY(QString networkConnectionType', native)
        self.assertIn('networkConnectionTypeChanged', native)
        self.assertIn('802-3-ethernet', native)
        self.assertIn('802-11-wireless', native)
        self.assertIn('QStringLiteral("Default")', native)
        self.assertIn('org.freedesktop.NetworkManager', native)
        self.assertIn('org.bluez', native)
        self.assertIn('anchors.right: parent.right', shell)
        self.assertIn('anchors.topMargin: root.statusStripTop', shell)
        self.assertIn('anchors.rightMargin: root.statusStripRightMargin', shell)
        self.assertIn('statusStripRightMargin: homeCategoryRailX', shell)
        self.assertIn('statusStripTop: selectedDomainY', shell)
        self.assertIn('compact: false', shell)
        self.assertIn('TextMetrics', (ROOT / "ui" / "StatusGlyph.qml").read_text())
        self.assertIn('tightBoundingRect.height', (ROOT / "ui" / "StatusGlyph.qml").read_text())
        self.assertIn('targetPaintedHeight', (ROOT / "ui" / "StatusGlyph.qml").read_text())
        self.assertIn('displayFamily', strip)
        self.assertIn('displayWeight', strip)
        self.assertIn('property real innerSpacing', strip)
        self.assertIn('property real groupSpacing', strip)
        self.assertIn('text: ": " + String(modelData.battery)', strip)

    def test_system_settings_is_controller_first_and_backend_driven(self) -> None:
        system_home = (ROOT / "ui" / "SystemHome.qml").read_text()
        system_space = (ROOT / "ui" / "SystemSpace.qml").read_text()
        self.assertIn('property var systemCategories:', QML)
        self.assertIn('property var systemSettings:', QML)
        self.assertIn('systemCategoryIndex = Math.max(0, systemCategoryIndex - 1)', QML)
        self.assertIn('systemCategoryIndex = Math.min(systemCategories.length - 1, systemCategoryIndex + 1)', QML)
        self.assertIn('request("/settings?category="', QML)
        self.assertIn('signal openRequested(int index)', system_home)
        self.assertIn('PageUp', QML)
        self.assertIn('PageDown', QML)
        self.assertIn('modelData.label', system_space)

    def test_navigation_cards_share_the_all_games_surface(self) -> None:
        navigation_card = (ROOT / "ui" / "NavigationCard.qml").read_text()
        navigation_surface = (ROOT / "ui" / "NavigationCardSurface.qml").read_text()
        store = (ROOT / "ui" / "StoreHome.qml").read_text()
        system = (ROOT / "ui" / "SystemHome.qml").read_text()
        library_surface = (ROOT / "ui" / "LibrarySpatialSurface.qml").read_text()
        self.assertIn("NavigationCardSurface {", navigation_card)
        self.assertIn("transmission: 1", navigation_surface)
        self.assertIn("bulgeStrength: 100", navigation_surface)
        self.assertIn("NavigationCard {", store)
        self.assertIn("NavigationCard {", system)
        self.assertIn("NavigationCardSurface {", library_surface)
        self.assertIn("selectionProgress", system)
        self.assertIn("function railX(relativeIndex)", system)
        self.assertIn("presentationStartX", system)
        self.assertIn("captureSelection()", system)
        self.assertIn("onActivated: root.openRequested(index)", system)
        self.assertIn("property url artworkSource", navigation_card)
        self.assertIn('property string artworkRole: "icon"', navigation_card)
        self.assertIn("artworkRole: root.artworkRole", navigation_card)
        self.assertIn('artworkSource: Qt.resolvedUrl(MudosAssetCatalog.suppliedArtwork("store"))', store)
        self.assertIn('artworkRole: "raster"', store)
        self.assertIn("function categoryArtwork(category)", (ROOT / "ui" / "LibraryHome.qml").read_text())
        self.assertIn("function categoryArtwork(category)", system)
        self.assertNotIn("border.width", (ROOT / "ui" / "NavigationCard.qml").read_text())
        self.assertNotIn("anchors.margins: -8", (ROOT / "ui" / "NavigationCard.qml").read_text())
        self.assertIn("onOpenRequested: root.openSystemCategory(index)", QML)
        self.assertIn("function openSystemCategory(index)", QML)
        self.assertNotIn("root.activate()\n            }", QML)

    def test_store_consumes_normalized_availability_without_install_behavior(self) -> None:
        store = (ROOT / "ui" / "StoreHome.qml").read_text()
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        self.assertIn('request.open("GET", apiUrl + "/available?provider=romm")', QML)
        self.assertIn('property var storeAvailableGames: []', QML)
        self.assertIn('property var storeCategories:', QML)
        self.assertIn('availability_state !== "available"', QML)
        self.assertIn('install_state !== "available"', QML)
        self.assertIn('categories.push({"label": label, "scope": scope})', QML)
        self.assertIn('emptyText: root.errorMessage !== "" ? root.errorMessage : "No games available"', store)
        self.assertIn('libraryGames: root.displayGames', store)
        self.assertIn('specialCardId: "steam-store"', store)
        self.assertIn('actionLabel: "Download"', store)
        self.assertIn('root.space === "store" ? "Download"', QML)
        self.assertIn('catalogueCard: true', (ROOT / "ui" / "LibrarySpace.qml").read_text())
        self.assertIn('MudosGlassItem {', (ROOT / "ui" / "GameCard.qml").read_text())
        self.assertNotIn('RecentHome {', store)
        self.assertIn('LibrarySpace {', store)
        self.assertIn('function moveVertical(delta)', store)
        self.assertIn('availableGames.length + categories.length + displayCategoryIndex >= 0', store)
        self.assertIn('String(game.game_id) === "steam-store"', store)
        self.assertIn('scope === "all"', store)
        self.assertIn('if (scope === "all")', store)
        self.assertIn('installGameRequested(game)', store)
        self.assertIn('game.provider === "steam"', store)
        self.assertIn('onInstallGameRequested: root.installGame(game)', QML)
        self.assertIn('request("/install/"', QML)
        self.assertIn('call_submit_job', bridge)
        self.assertNotIn('steam://install', QML + store)
        self.assertIn('game.provider === "romm"', store)
        self.assertIn('call_list_available_games', bridge)
        recent = ((ROOT / "ui" / "RecentHome.qml").read_text()
                  + (ROOT / "ui" / "RecentCardPresentation.qml").read_text())
        self.assertIn('actionLabel: root.install_state === "available"', recent)
        self.assertIn('text: card.actionLabel', (ROOT / "ui" / "GameCard.qml").read_text())

    def test_non_game_portrait_artwork_assets_are_replaceable(self) -> None:
        artwork = ROOT / "ui" / "artwork"
        expected = {
            "platform-all.svg", "platform-pc.png", "store.png",
            "platform-nes.png", "platform-snes.png", "platform-genesis.png",
            "platform-gb.png", "platform-gbc.png", "platform-gba.png",
            "platform-nds.png", "platform-gamecube.png", "platform-wii.png",
            "platform-switch.png", "platform-ps1.png", "platform-ps2.png",
            "platform-ps3.png",
            "system-display.svg", "system-audio.svg", "system-network.svg",
            "system-bluetooth.svg", "system-controllers.svg", "system-storage.svg",
            "system-system.svg", "system-lulu.svg", "README.md",
        }
        self.assertTrue(expected.issubset({path.name for path in artwork.iterdir()}))
        self.assertTrue((artwork / "navigation").is_dir())
        self.assertTrue((artwork / "glyphs" / "metadata").is_dir())
        for path in artwork.rglob("*"):
            if not path.is_file():
                continue
            self.assertGreater(path.stat().st_size, 0)

    def test_home_uses_one_fixed_content_stage_and_compact_library_object(self) -> None:
        self.assertIn("readonly property real headingCardGap: design(21)", QML)
        self.assertIn("readonly property real homeHintTopY: height - design(45)", QML)
        self.assertIn("homeContentOriginY: homeHintTopY - acceptedRecentCardHeight - headingCardGap", QML)
        self.assertIn("selectedDomainY: homeActiveContentOriginY - homeHeadingCardClearance", QML)
        self.assertIn("titleHeight * 0.5)", QML)
        self.assertIn("acceptedRecentCardHeight", QML)
        self.assertIn("y: root.titleRailChildY(index)", QML)
        self.assertIn("function domainOffset(index)", QML)
        self.assertIn("y: root.homeActiveContentOriginY", QML)
        self.assertIn("root.homeCategoryTransitioning", QML)
        self.assertIn("homeCategoryTarget === 2", QML)
        self.assertIn("homeCategoryFrom === 2", QML)
        self.assertIn("homeCategoryTarget === 3", QML)
        self.assertIn("homeCategoryRevealHeight(index)", QML)
        self.assertIn("var titleHeight = titleItem ? titleItem.height : activeHeadingHeight", QML)
        self.assertIn("desiredCategoryIndex", QML)
        self.assertIn("function startNextHomeCategoryHop(chained)", QML)
        self.assertIn("homeCategoryHopDuration", QML)
        self.assertIn("homeCategoryHopDuration = chained ? 100 : 250", QML)
        self.assertIn("root.titleRailY = root.titleRailTargetY", QML)
        self.assertIn("duration: root.homeCategoryHopDuration", QML)
        self.assertIn("if (homeCategoryAnimation.running)", QML)
        self.assertIn("id: libraryReveal", QML)
        self.assertIn('surfaceVisible: root.space === "library" || root.space === "store"', QML)
        self.assertIn('|| root.libraryTransitioning', QML)
        self.assertIn("x: -root.homeContentRailX", QML)
        self.assertIn("id: homeCardViewport", QML)
        self.assertIn("id: systemReveal\n                    x: -root.homeContentRailX", QML)
        self.assertIn("id: systemHomeRail\n                        x: root.homeContentRailX", QML)
        self.assertIn("id: homeCardViewport\n                x: 0", QML)
        self.assertIn("id: homeContent\n                x: root.homeContentRailX", QML)
        self.assertIn("height: root.homeBottomBandCenterY - root.homeActiveContentOriginY", QML)
        self.assertIn("clip: true", QML)
        self.assertIn("opacity: 1", QML)
        self.assertNotIn("homeCategoryOpacityProgress", QML)
        self.assertNotIn("homeCategoryOpacityAnimation", QML)
        self.assertNotIn("root.domainIndex * 40", QML)
        library_home = (ROOT / "ui" / "LibraryHome.qml").read_text()
        self.assertIn('"PC Games", "scope": "pc"', library_home)
        self.assertIn("NavigationCard", library_home)
        self.assertIn("presentationStartX", library_home)
        self.assertIn("function railX(relativeIndex)", library_home)
        self.assertIn("targetX: libraryHome.railX(index - libraryHome.selectedIndex)", library_home)
        self.assertIn("moveLibraryLanding", QML)
        self.assertIn("selectedIndex: root.collectionIndex", QML)
        self.assertIn("property real cardHeight", library_home)
        self.assertIn("height: libraryHome.cardHeight", library_home)
        self.assertIn("width: libraryHome.compactCardWidth", library_home)
        self.assertIn('artworkSource: Qt.resolvedUrl("artwork/" + libraryHome.categoryArtwork(modelData.scope)[0])', library_home)
        catalog = (ROOT / "ui" / "MudosAssetCatalog.js").read_text()
        self.assertIn('nes: ["platforms/romm/nes.svg", "raster"]', catalog)
        self.assertIn('all: ["platforms/romm/default.ico", "raster"]', catalog)
        for asset in ("nes.svg", "snes.svg", "genesis.svg", "gb.svg", "gbc.svg",
                      "gba.svg", "nds.svg", "ngc.svg", "wii.svg", "switch.svg",
                      "psx.svg", "ps2.svg", "ps3.svg", "default.ico"):
            self.assertTrue((ROOT / "ui/artwork/platforms/romm" / asset).is_file())
        self.assertIn('artworkRole: libraryHome.categoryArtwork(modelData.scope)[1]', library_home)
        self.assertIn("canonicalCoordinateRoot", library_home)
        self.assertNotIn("allGamesSceneOrigin", library_home)
        self.assertNotIn("gameCount", library_home)
        self.assertNotIn("selectedGame", library_home)

    def test_cards_preserve_portrait_artwork_and_library_density(self) -> None:
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        self.assertIn("visible: card.focalChromeOpacity > 0", game_card)
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertIn("compactArtworkWidth * 1.5", game_card)
        self.assertIn("compactArtworkWidth", game_card)
        self.assertIn("compactArtworkHeight", game_card)
        self.assertIn("Image.PreserveAspectFit", game_card)
        self.assertIn("presentationProgress < 1", game_card)
        self.assertIn("readonly property int gridColumns: 6", library_space)
        self.assertIn("gridLeftInset", library_space)
        self.assertIn("gridTop - gridTopInset", library_space)
        self.assertIn("gridRegionHeight + gridTopInset", library_space)
        self.assertIn("(usableGridWidth - (gridColumns - 1) * gridGap) / gridColumns", library_space)
        self.assertIn("fullscreenPanelBevelWidth: 6 * uiScale", library_space)
        self.assertIn("gridHorizontalGrowth", library_space)
        self.assertIn("gridVerticalGrowth", library_space)
        self.assertIn("(fullscreenPanelCardSelectionScale - 1.0) * libraryCardHeight", library_space)
        self.assertIn("fullscreenPanelBorderWidth: 0", library_space)
        self.assertIn("fullscreenPanelTransmission: 1", library_space)
        self.assertNotIn("border.color: luluPalette.libraryHighlight", library_space)
        self.assertIn("scale: focused ? librarySpace.fullscreenPanelCardSelectionScale : 1", library_space)
        self.assertIn("z: focused ? 2 : 1", library_space)
        self.assertIn("unfocusedBrightness: 0.8", library_space)
        self.assertIn("librarySpace.unfocusedBrightness", library_space)
        self.assertIn("property real focusBrightness: 1", game_card)
        self.assertIn("opacity: card.focused ? 1 : 0.84", game_card)
        self.assertIn("focusBrightness: root.focused ? 1 : 0.84", (ROOT / "ui" / "RecentCardPresentation.qml").read_text())
        self.assertIn("focusBrightness: root.selectedOpacityOwner ? 1 : 0.84", (ROOT / "ui" / "NavigationCard.qml").read_text())
        self.assertIn("readonly property real headerToGridGap: currentHeaderToGridGap / 2", library_space)
        self.assertIn("gridTop: contentBottom - gridContentFootprintHeight", library_space)
        self.assertIn("horizontalCardWidth", library_space)
        self.assertIn("libraryCardHeight: libraryCardWidth * 1.55", library_space)
        self.assertIn("expandedCardScale: 0.92", library_space)
        self.assertIn("* expandedCardScale", library_space)
        self.assertIn("headingBottom: pageHeading.y + pageHeading.height", library_space)
        self.assertIn("firstRowTop: gridTop - selectedGrowth", library_space)
        self.assertIn("categoryRailHeight: categoryGlyphMetrics.height + 8 * uiScale", library_space)
        self.assertIn("requiredTwoRowHeight", library_space)
        self.assertIn("id: gridViewport", library_space)
        self.assertIn("clip: true", library_space)
        self.assertIn("GridView {", library_space)
        self.assertIn("cacheBuffer: 2 * gridRowStep", library_space)
        self.assertIn("contentY: librarySpace.firstVisibleRow * librarySpace.gridRowStep", library_space)
        self.assertIn("highlightRangeMode: GridView.NoHighlightRange", library_space)
        self.assertIn("highlightFollowsCurrentItem: false", library_space)
        self.assertIn("parent.height - 16 * uiScale - gridBottomInset", library_space)
        self.assertIn("gridRegionHeight: requiredTwoRowHeight", library_space)
        self.assertIn("property real contentBottom", library_space)
        self.assertIn("gridContentFootprintHeight", library_space)
        self.assertIn("gridTop: contentBottom - gridContentFootprintHeight", library_space)
        self.assertIn("libraryCardHeight + gridGap + libraryCardHeight + selectedGrowth", library_space)
        self.assertIn("firstRowTop: gridTop - selectedGrowth", library_space)
        self.assertIn("property real contentSideMargin", library_space)
        self.assertIn("parent.width - 2 * contentSideMargin", library_space)
        self.assertIn("gridVisualWidth: gridSlotWidth + 2 * gridHorizontalGrowth", library_space)
        self.assertIn("contentOriginX: (parent.width - gridVisualWidth) / 2", library_space)
        self.assertIn("gridSlotLeft: contentOriginX + gridHorizontalGrowth", library_space)
        self.assertIn("y: 81 * uiScale", library_space)
        self.assertIn("id: categoryViewport", library_space)
        self.assertIn("x: contentOriginX", library_space)
        self.assertIn("categoryFadeWidth: categoryGlyphAdvance * 10", library_space)
        self.assertIn("categoryGlyphAdvance: categoryGlyphMetrics.advanceWidth", library_space)
        self.assertIn("readonly property real glyphCenterX", library_space)
        self.assertIn("categoryViewport.x + categoryRail.x + parent.x", library_space)
        self.assertIn("opacity: categoryStateOpacity * edgeFadeOpacity", library_space)
        self.assertIn("model: categoryLabel.length", library_space)
        self.assertNotIn("ShaderEffectSource", library_space)
        self.assertNotIn("category-rail-fade", library_space)
        self.assertIn("TextMetrics {", library_space)
        self.assertIn("fullscreenHeight: root.expandedShellHeight", shell)
        self.assertIn("fullscreenY: root.expandedShellY", shell)
        self.assertIn("y: 32 * uiScale", library_space)
        self.assertIn("height: parent.height - 48 * uiScale", library_space)
        self.assertIn("property real gameContentOpacity: 1", library_space)
        self.assertIn("opacity: librarySpace.contentOpacity * librarySpace.gameContentOpacity", library_space)
        self.assertIn("duration: librarySpace.gameContentOpacity === 0 ? 100 : 200", library_space)
        self.assertIn("signal categoryContentHidden()", library_space)
        self.assertIn("onCategoryContentHidden: root.displayCategoryIndex = root.categoryIndex", (ROOT / "ui" / "StoreHome.qml").read_text())
        self.assertNotIn("Repeater {\n                model: libraryGames", library_space)
        self.assertNotIn("scrollFadeStart", library_space)
        self.assertNotIn("scrollFadeEnd", library_space)
        self.assertIn("horizontalAlignment: Text.AlignHCenter", game_card)
        self.assertIn("verticalAlignment: Text.AlignVCenter", game_card)
        self.assertIn("elide: Text.ElideRight", game_card)
        self.assertIn("font.weight: card.compact || card.compactEndpointWidth > 0 ? Font.Bold : Font.Normal", game_card)
        self.assertIn("card.compact ? 13 * 0.8 : 16", game_card)
        self.assertIn("layer.enabled: card.librarySurfaceMaterial", game_card)
        self.assertIn("shadowOpacity: 0.35", game_card)

    def test_recent_has_distinct_focal_and_compact_geometry(self) -> None:
        recent = ((ROOT / "ui" / "RecentHome.qml").read_text()
                  + (ROOT / "ui" / "RecentCardPresentation.qml").read_text())
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        artwork_shader = (ROOT / "ui" / "shaders" / "card-rounded.frag").read_text()
        self.assertIn("property real focalCardHeight", recent)
        self.assertIn("x: startX + (recentHome.railX(toRelativeIndex) - startX) * railProgress", recent)
        self.assertIn("focalChromeOpacity", recent)
        self.assertIn("startChrome", recent)
        self.assertIn("startCompactTitle", recent)
        self.assertIn('console.log("RECENT_RETARGET", "capture"', recent)
        self.assertIn('console.log("RECENT_RETARGET", "target"', recent)
        self.assertIn("duration: 500", recent)
        self.assertIn("easing.type: Easing.OutQuint", recent)
        self.assertIn('property: "transitionFadeProgress"', recent)
        self.assertIn("z: 2", game_card)
        self.assertIn("property real compactCardWidth", recent)
        self.assertIn("height: compactCardHeight", recent)
        self.assertIn("compactCardWidth + railGap", recent)
        self.assertIn("compactCardWidth: root.compactGameCardWidth", shell)
        self.assertIn("compactCardHeight: root.compactCardHeight", shell)
        self.assertIn("cardHeight: root.homeNavigationCardHeight", shell)
        self.assertIn("readonly property bool recentFocal", game_card)
        self.assertIn("property real compactTitleOpacity", game_card)
        self.assertIn("card.compactEndpointWidth > 0", game_card)
        self.assertIn('Qt.formatDateTime', game_card)
        self.assertIn('text: card.actionLabel || "Play"', game_card)
        self.assertIn("String.fromCodePoint(0xF04B)", game_card)
        self.assertIn("font.family: card.typography ? card.typography.iconFamily", game_card)
        self.assertIn("spacing: 8 * card.uiScale", game_card)
        self.assertIn("maximumLineCount: 2", game_card)
        self.assertIn("wrapMode: Text.WordWrap", game_card)
        self.assertIn("property real focalLayoutCardWidth: 0", game_card)
        self.assertIn("focalTitleLayoutWidth", game_card)
        self.assertIn("id: focalTitleLayoutMeasure", game_card)
        self.assertIn("focalLayoutCardWidth: root.focalCardWidth", recent)
        self.assertIn("property real artworkRadius: card.mix", game_card)
        self.assertIn("property real artworkRadius", game_card)
        self.assertIn("cornerRadius: artworkFrame.artworkRadius / Math.min(width, height)", game_card)
        self.assertNotIn("diagnosticMode", game_card)
        self.assertNotIn("vec4(vec3(alpha), alpha)", artwork_shader)
        self.assertIn("property real artworkBorderAlpha: 0.15", game_card)
        self.assertIn("property vector2d artworkSize", game_card)
        self.assertIn("float pixelWidth = borderWidthPx / min(artworkSize.x, artworkSize.y)", artwork_shader)
        self.assertIn("float border = smoothstep", artwork_shader)
        self.assertIn("luluPalette.artworkSurface", game_card)
        self.assertIn('card.compact ? 13 * 0.8 : 16', game_card)
        self.assertIn("sourceItem: artworkSource", game_card)
        self.assertIn("hideSource: true", game_card)
        self.assertIn("sourceItem: artworkSource\n            hideSource: true\n            visible: false", game_card)
        self.assertIn("readonly property real focalMargin", game_card)
        self.assertIn("property real focalScale", game_card)
        self.assertIn('property string presentationState: "COMPACT"', game_card)
        self.assertIn('presentationState: game_id === recentHome.selectedGameId ? "FOCUSED" : "COMPACT"', recent)
        self.assertIn("property string selectedGameId", recent)
        self.assertIn('required property string modelData', library_space)
        self.assertIn('transitionState: root.libraryTransitionState', shell)
        self.assertIn('property string libraryTransitionState: "RESTING"', shell)
        self.assertIn("focalScale: 0.67", (ROOT / "ui" / "ConsoleShell.qml").read_text())
        self.assertIn("fragmentShader", game_card)
        self.assertIn("canonicalTexture", game_card)
        self.assertIn("transparentOutsideMask: card.nativeGlassTransparentOutsideMask", game_card)
        self.assertIn("transparentOutsideMask", (ROOT / "ui" / "NavigationCardSurface.qml").read_text())
        self.assertIn("MudosGlassItem", game_card)
        self.assertIn("backdrop: card.canonicalTexture", game_card)
        self.assertIn("canonicalCoordinateRoot", game_card)
        self.assertIn("card.mapToItem(canonicalCoordinateRoot, 0, 0)", game_card)
        self.assertIn("liveSceneCoordinates: true", recent)
        self.assertIn("opticsStage: root.presentationProgress > 0 ? 7 : -1", recent)
        self.assertIn("layoutDependency = card.x + card.y + card.width + card.height", game_card)
        self.assertIn("canonicalRect: card.nativePlayCanonicalRect", game_card)
        self.assertIn("readonly property real focalMargin", game_card)
        self.assertIn("focalMargin + artworkWidth + focalMargin", game_card)
        self.assertIn("readonly property var focalMetadataRows", game_card)
        self.assertNotIn('"Genres  "', game_card)
        self.assertNotIn('"Last Played  "', game_card)
        self.assertIn('"SUPPORTED"', game_card)
        self.assertIn('"NOT_SUPPORTED"', game_card)
        self.assertIn('"UNKNOWN"', game_card)
        self.assertIn('"No Local Multiplayer"', game_card)
        self.assertIn('"No Online Multiplayer"', game_card)
        for glyph in ('"\\uf02c"', '"\\uf1da"', '"\\uf017"',
                      '"\\uf0c0"', '"\\uf0ac"', '"\\ue27f"',
                      '"\\uf11b"', '"\\uf1e6"'):
            self.assertIn(glyph, game_card)
        self.assertIn('text: protonDb', game_card)
        self.assertIn('card.displayPlatform', game_card)
        self.assertIn('card.displayProvider', game_card)
        self.assertIn("focalMetadataGlyphColumnWidth", game_card)
        self.assertIn("id: metadataGlyphColumn", game_card)
        self.assertIn("anchors.fill: parent", game_card)
        self.assertIn("anchors.left: parent.left", game_card)
        self.assertIn('focalMetadataGlyphColumnWidth: 18', game_card)
        self.assertIn('tightBoundingRect', game_card)
        self.assertIn('metadataGlyphMetrics.advanceWidth', game_card)
        self.assertIn("horizontalAlignment: Text.AlignHCenter", game_card)
        self.assertNotIn('namespace: "metadata"', game_card)
        self.assertIn("Total Playtime", game_card)
        self.assertIn("anchors.right: parent.right", game_card)
        self.assertIn("anchors.bottom: parent.bottom", game_card)
        self.assertNotIn("card.game.provider.toUpperCase()", game_card)

    def test_orbit_backdrop_uses_qsb_and_plain_fallback(self) -> None:
        backdrop = (ROOT / "ui" / "OrbitBackdrop.qml").read_text()
        shader_builder = (ROOT / "scripts" / "build-orbit-shader.sh").read_text()
        adapter = (ROOT / "scripts" / "build-orbit-qsb.py").read_text()
        self.assertIn('fragmentShader: "shaders/orbit-wave.frag.qsb"', backdrop)
        self.assertIn("color: luluPalette.backdrop", backdrop)
        self.assertIn("ShaderEffect.Compiled", backdrop)
        self.assertIn("--qt6", shader_builder)
        self.assertIn("wave.frag", shader_builder)
        for uniform in ("u_resolution", "u_origin", "u_canvas", "u_time", "u_brightness", "u_visibility", "u_primary", "u_secondary", "u_surface", "u_error"):
            self.assertIn(uniform, adapter)
        self.assertIn('replace("gl_FragColor", "fragColor")', adapter)

    def test_orbit_presentation_uses_coordinator_and_shared_canonical_texture(self) -> None:
        source = (ROOT / "ui" / "OrbitRenderSource.qml").read_text()
        coordinator = (ROOT / "ui" / "PresentationCoordinator.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        self.assertIn("presentationCoordinator", source)
        self.assertIn("orbitShaderTime", source)
        self.assertIn("orbitVisibility", source)
        self.assertNotIn("NumberAnimation on shaderTime", source)
        self.assertIn("orbitBaseTimeAnimation", coordinator)
        self.assertIn("orbitIntroCorrection", coordinator)
        self.assertIn("orbitExitCorrection", coordinator)
        self.assertIn('id: orbitTexture', shell)
        self.assertIn('sourceItem: orbitRenderSource', shell)
        self.assertIn('texture: orbitTexture', shell)
        self.assertIn('canonicalTexture: orbitTexture', shell)
        self.assertIn('canonicalCoordinateRoot: orbitRenderSource', shell)

    def test_controller_x_routes_to_shared_game_options_action(self) -> None:
        native_shell = (ROOT / "native" / "lulu-shell.cpp").read_text()
        self.assertIn('{SDL_GAMEPAD_BUTTON_WEST, "options"}', native_shell)
        self.assertNotIn('{SDL_GAMEPAD_BUTTON_NORTH, "options"}', native_shell)
        self.assertIn('{"options", "openSelectedGameOptions"}', native_shell)
        self.assertIn("function openSelectedGameOptions()", QML)
        self.assertIn("openGameOptions(selectedGameForOptions)", QML)

    def test_game_options_owns_confirm_and_ignores_reopen(self) -> None:
        native_shell = (ROOT / "native" / "lulu-shell.cpp").read_text()
        self.assertIn('{SDL_GAMEPAD_BUTTON_SOUTH, "confirm"}', native_shell)
        self.assertIn("if (gameOptionsOpen) {\n            activateGameOptions()", QML)
        self.assertIn("if (gameOptionsOpen)\n            return\n        if (selectedGameForOptions)", QML)
        self.assertIn('if (gameOptionsOpen) {\n            if (gameOptionsView === "menu")', QML)
        self.assertIn('closeGameOptions()\n            else', QML)

    def test_shell_profile_routes_semantic_events_to_qt_keys(self) -> None:
        for button, key in (
            ("DPadUp", "KeyUp"),
            ("DPadDown", "KeyDown"),
            ("DPadLeft", "KeyLeft"),
            ("DPadRight", "KeyRight"),
            ("South", "KeyEnter"),
            ("East", "KeyBackspace"),
            ("LeftBumper", "KeyPageUp"),
            ("RightBumper", "KeyPageDown"),
        ):
            self.assertIn(f"button: {button}", SHELL_PROFILE)
            self.assertIn(f"keyboard: {key}", SHELL_PROFILE)
        self.assertIn("button: North", SHELL_PROFILE)
        self.assertIn("keyboard: KeyX", SHELL_PROFILE)

    def test_game_options_preserves_contextual_two_level_structure(self) -> None:
        options = (ROOT / "ui" / "GameOptions.qml").read_text()
        for entry in ("Change Match", "Edit Metadata", "Edit Title", "Clear Title Override"):
            self.assertIn(entry, options)
        self.assertIn('"Remove Image"', options)
        self.assertIn('"Restore Image"', options)
        self.assertIn("metadataMutation", QML)
        self.assertIn("/metadata/search?game_id=", QML)
        self.assertIn("function back()", QML)

    def test_library_navigation_separates_grid_and_collection_controls(self) -> None:
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        self.assertIn("function moveLibraryVertical(delta)", shell)
        self.assertIn("var column = libraryIndex % 6", shell)
        self.assertIn("var target = row * 6 + column", shell)
        self.assertIn("moveLibraryCollection(-1)", shell)
        self.assertIn("moveLibraryCollection(1)", shell)
        self.assertIn('action: "navigation"', shell)
        self.assertIn('action: "previousCollection"', shell)
        self.assertIn('action: "nextCollection"', shell)
        self.assertIn('label: root.selectedCategoryIndex === 3 ? "Navigate / Games"', shell)
        self.assertIn('property bool libraryTransitioning: false', shell)
        self.assertIn('property: "libraryTransitionProgress"', shell)
        self.assertIn('duration: 500', shell)
        self.assertIn('easing.type: Easing.OutQuint', shell)
        self.assertIn('LibrarySpatialSurface {', shell)
        self.assertIn('homeX: root.homeContentRailX', shell)
        self.assertIn('fullscreenWidth: root.expandedShellWidth', shell)
        self.assertIn('contentBottom: root.expandedContentBottom', shell)
        self.assertIn('contentSideMargin: root.expandedContentSideMargin', shell)
        self.assertIn('expandedContentSideMargin: design(120)', shell)
        self.assertIn('expandedGridGap: design(14)', shell)
        self.assertIn('expandedShellSideMargin:', shell)
        self.assertIn('(width - expandedGridVisualWidth) / 2 - expandedGridGap', shell)
        self.assertIn('expandedShellTop: statusStripBottom', shell)
        self.assertIn('expandedSurfaceChromeGap: design(18)', shell)
        self.assertIn('expandedHintRowTop: interactionRail.y + expandedHintRow.y', shell)
        self.assertIn('expandedShellBottom: expandedHintRowTop', shell)
        self.assertIn('root.space === "store"', shell)
        self.assertIn('label: root.space === "library" ? "Launch" : "Download"', shell)
        spatial_surface = (ROOT / "ui" / "LibrarySpatialSurface.qml").read_text()
        self.assertNotIn("z: 1", spatial_surface)
        self.assertIn('contentOpacity: root.libraryContentOpacity', shell)
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertNotIn("GlassSurface {", library_space)
        library_home = (ROOT / "ui" / "LibraryHome.qml").read_text()
        self.assertIn("NavigationCard", library_home)
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        self.assertIn("card.librarySurfaceMaterial", game_card)
        self.assertIn("card.librarySurfaceMaterial ? 0", game_card)
        self.assertIn('action: "confirm"', shell)
        self.assertIn("property int libraryFirstVisibleRow: 0", shell)
        self.assertIn("if (row >= libraryFirstVisibleRow + 2)", shell)
        self.assertIn("firstVisibleRow: root.libraryFirstVisibleRow", shell)

    def test_launch_errors_are_not_reported_as_catalogue_failures(self) -> None:
        self.assertIn('encodeURIComponent(game.game_id)', QML)
        self.assertIn('}, "Launch failed", generation, function()', QML)

    def test_home_launch_waits_for_feedback_exit_and_hidden_boundary(self) -> None:
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        coordinator = (ROOT / "ui" / "PresentationCoordinator.qml").read_text()
        recent = (ROOT / "ui" / "RecentHome.qml").read_text()
        self.assertIn("signal playFeedbackCompleted()", game_card)
        self.assertIn("card.playFeedbackCompleted()", game_card)
        self.assertIn("function beginPendingHomeLaunch", QML)
        self.assertIn("function completePendingHomeLaunch", QML)
        self.assertIn("function finishHiddenHomeLaunch", QML)
        self.assertIn("beginContentExit()", QML)
        self.assertIn("contentHiddenReached", coordinator)
        self.assertIn("freezePresentation", recent)
        self.assertIn("reconcilePresentation", recent)
        self.assertIn("HOME_HIDDEN_LAUNCH_HANDOFF", QML)
        self.assertNotIn("launchGame(visibleRecentGame)", QML)
        self.assertNotIn("PauseAnimation { duration: 160", QML)

    def test_return_observer_is_independent_of_launch_status_polling(self) -> None:
        self.assertIn("property bool returnWatchActive: false", QML)
        self.assertIn("function startReturnWatch()", QML)
        self.assertIn("function refreshReturnState(generation)", QML)
        self.assertIn("function evaluateReturnReadiness(source)", QML)
        self.assertIn('traceLaunchEvent("RETURN_WATCH_STARTED"', QML)
        self.assertIn('traceLaunchEvent("RETURN_STATE_OBSERVED"', QML)
        self.assertIn('traceLaunchEvent("RETURN_PRESENTATION_OBSERVED"', QML)
        self.assertIn('traceLaunchEvent("RETURN_READY"', QML)
        self.assertIn('traceLaunchEvent("RETURN_WATCH_STOPPED"', QML)
        self.assertIn("startReturnWatch()", QML[QML.index("function finishHiddenHomeLaunch") :])
        self.assertIn("returnObserverTimer.start()", QML)
        self.assertIn("returnObserverTimer.stop()", QML)
        self.assertIn("returnStateObserved && presented", QML)
        self.assertIn("stopReturnWatch(\"launch-failed\")", QML)

    def test_recent_reconcile_is_deferred_until_presented(self) -> None:
        presented = QML.split("function onContentPresentedReached()", 1)[1].split(
            "function traceLaunchMutation", 1)[0]
        prepare = QML.split("function prepareAndPresentHome()", 1)[1].split(
            "function observeGamePresentation", 1)[0]
        handoff = QML.split("function finishHiddenHomeLaunch()", 1)[1].split(
            "function installGame", 1)[0]
        self.assertIn("returnPresentationPending", presented)
        self.assertIn("recentHome.reconcilePresentation()", presented)
        self.assertIn("returnPresentationPending = false", presented)
        self.assertNotIn("recentHome.reconcilePresentation()", prepare)
        self.assertNotIn("recentHome.reconcilePresentation()", handoff)
        self.assertIn("returnPresentationPending = true", prepare)
        self.assertIn('traceLaunchEvent("PRESENTATION_FREEZE"', QML)
        self.assertIn('traceLaunchEvent("RECENT_PRESENTATION_RELEASED"', QML)
        self.assertIn("returnPresentationPending", QML[QML.index("readonly property bool homeLaunchGated") :])

    def test_presented_reconcile_happens_before_input_unlock(self) -> None:
        presented = QML.split("function onContentPresentedReached()", 1)[1].split(
            "function traceLaunchMutation", 1)[0]
        self.assertLess(presented.index("recentHome.reconcilePresentation()"),
                        presented.index("HOME_INPUT_UNLOCKED"))

    def test_recent_reconcile_requests_authority_before_releasing_frozen_rows(self) -> None:
        recent = (ROOT / "ui" / "RecentHome.qml").read_text()
        reconcile = recent.split("function reconcilePresentation()", 1)[1].split(
            "function selectionCardVelocityAt", 1)[0]
        self.assertLess(reconcile.index("selectionIndexRequested(reconciledIndex)"),
                        reconcile.index("presentationFrozen = false"))

    def test_library_and_store_category_rail_uses_content_sized_selected_anchor(self) -> None:
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertIn("id: categoryViewport", library_space)
        self.assertIn("clip: true", library_space)
        self.assertIn("id: categoryRail", library_space)
        self.assertIn("selectedCategoryDelegate", library_space)
        self.assertIn("x: selectedCategoryDelegate ? -selectedCategoryDelegate.x : 0", library_space)
        self.assertIn("width: categoryRowWidth", library_space)
        self.assertIn("spacing: librarySpace.categoryGap", library_space)
        self.assertIn("Behavior on x", library_space)
        self.assertIn("Easing.OutQuint", library_space)
        self.assertNotIn("width: librarySpace.categoryPitch", library_space)
        self.assertIn("horizontalAlignment: Text.AlignHCenter", library_space)
        self.assertIn("LibrarySpace {", (ROOT / "ui" / "StoreHome.qml").read_text())
        store_home = (ROOT / "ui" / "StoreHome.qml").read_text()
        self.assertIn('headingText: "AVAILABLE TO DOWNLOAD"', store_home)
        self.assertIn('displayTitle: "Available to Download"', store_home)
        self.assertIn('root.space === "store"', QML)
        self.assertIn("text: root.domains[index].toUpperCase()", QML)
        self.assertIn("font.letterSpacing: 5 * root.uiScale", QML)
        self.assertIn("luluPalette.headingAccent", QML)
        self.assertIn('progress: root.libraryTransitionProgress', QML)
        self.assertIn('property bool storeTransitioning: false', QML)
        self.assertIn('presentationTarget = "store"', QML)
        self.assertIn('root.space = root.presentationTarget', QML)

    def test_launch_status_is_transactional_and_catalogue_focus_is_identity_based(self) -> None:
        self.assertIn('property string launchStatus: "idle"', QML)
        self.assertIn("property int launchGeneration: 0", QML)
        self.assertIn("property string launchToken: \"\"", QML)
        self.assertIn("property int launchStateSerial: 0", QML)
        self.assertIn("property int launchStateRank: 0", QML)
        self.assertIn("function applyLaunchState(state, generation)", QML)
        self.assertIn("state.launch_token", QML)
        self.assertIn('readonly property string recentSelectedGameId:', QML)
        self.assertIn("onSelectionGameChanged", QML)
        self.assertNotIn('message = "Launch requested"', QML)
        self.assertIn("if (stateRank < launchStateRank)", QML)
        self.assertIn('state.lifecycle === "presentation_pending"', QML)
        self.assertNotIn('launchStatus === "launching" || launchStatus === "running"', QML)
        self.assertIn("anchors.fill: parent", QML)
        self.assertIn("launchOverlayRetired = true", QML)
        self.assertIn("visible: root.launchOverlayEffectiveVisible", QML)
        self.assertIn("launchToken = data.token", QML)

        self.assertIn("refreshLaunchLog(root.launchGeneration)", QML)
        self.assertLess(QML.index("launchToken = data.token"), QML.index("            refreshLaunchState(generation)"))
        self.assertLess(QML.index("retireLaunchOverlay(generation)"), QML.index("function refreshLaunchLog(generation)"))
        self.assertIn('request("/cancel", "POST"', QML)
        self.assertIn('value === "back"', QML)
        self.assertIn('launchTitle = "Steam Store"', QML)
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        self.assertIn('self.launch_logs.start("steam-store")', bridge)


    def test_steam_overlay_has_game_presentation_shell_return_failsafe(self) -> None:
        self.assertIn("property bool shellWasLeft: false", QML)
        self.assertIn("function finishLaunchOnShellReturn()", QML)
        self.assertIn("root.shellWasLeft = true", QML)
        self.assertIn("root.shellWasLeft = true", QML)
        self.assertIn("if (root.shellWasLeft)", QML)
        self.assertIn("function prepareAndPresentHome()", QML)
        self.assertIn("launchLifecycle !== \"shell\"", QML)
        self.assertIn("launchLogTimer.stop()", QML)
        self.assertIn("launchLogLines = []", QML)
        self.assertIn("launchGeneration++", QML)
        self.assertIn('root.launchGameId.indexOf("steam:") === 0', QML)

    def test_ui_audio_engine_has_semantic_voices_and_safety_rules(self) -> None:
        engine = (ROOT / "ui" / "UiAudioEngine.qml").read_text()
        for semantic in ("navigate", "confirm", "back", "error"):
            self.assertIn(f'{semantic}Source: "sounds/ui-{semantic}.wav"', engine)
            self.assertIn(f'id: {semantic}VoiceComponent', engine)
        self.assertIn("function play(semantic)", engine)
        self.assertIn("function voiceFor(semantic)", engine)
        self.assertIn("debounceInterval: 55", engine)
        self.assertIn("maxVoices: 3", engine)
        self.assertIn("voice.status !== SoundEffect.Ready", engine)
        self.assertIn("activeVoiceCount() >= maxVoices", engine)
        self.assertIn("voice.stop()", engine)
        self.assertIn("function stopAll()", engine)
        self.assertIn("function loaderFor(semantic)", engine)
        self.assertIn("property string pendingSemantic", engine)
        self.assertIn("onLoaded: root.tryPlayPending()", engine)
        self.assertNotIn('source: "UiAudioEngine.qml"', (ROOT / "ui" / "MudosGuide.qml").read_text())
        self.assertIn('source: "UiAudioEngine.qml"', QML)
        self.assertNotIn("onValueChanged", engine)

    def test_ui_audio_assets_are_canonical_and_replaceable(self) -> None:
        manifest = (ROOT / "ui" / "sounds" / "README.md").read_text()
        for filename in ("ui-navigate.wav", "ui-confirm.wav", "ui-back.wav", "ui-error.wav"):
            self.assertIn(f"`{filename}`", manifest)
        self.assertIn("does not\nrequire a", manifest)

if __name__ == "__main__":
    unittest.main()
