import unittest
from pathlib import Path


ROOT = Path(__file__).parents[1]
QML = (ROOT / "ui" / "ConsoleShell.qml").read_text()
SHELL_PROFILE = (ROOT / "config" / "inputplumber" / "profiles" / "shell.yaml").read_text()


class ConsoleUiTests(unittest.TestCase):
    def test_qml_preserves_card_to_space_shell_interaction(self) -> None:
        self.assertIn('property var domains: ["System", "Store", "Library", "Recent"]', QML)
        self.assertIn("property int domainIndex: 3", QML)
        self.assertIn('property string space: "home"', QML)
        self.assertIn('space = "library"', QML)
        self.assertIn('space = "home"', QML)
        self.assertIn('readonly property string apiUrl:', QML)
        self.assertIn("function activate()", QML)
        self.assertIn("function moveDomain(delta)", QML)
        self.assertIn('message = "Store space is not implemented"', QML)
        self.assertIn('message = "System space is not implemented"', QML)
        self.assertIn('request("/?scope=recent"', QML)
        self.assertIn('readonly property string libraryScope:', QML)
        self.assertNotIn("/dev/input", QML)
        self.assertNotIn("Social", QML)

    def test_extracted_ui_primitives_preserve_real_game_card_data(self) -> None:
        for filename in ("GameCard.qml", "RecentHome.qml", "LibraryHome.qml", "LibrarySpace.qml", "PlaceholderHome.qml"):
            self.assertTrue((ROOT / "ui" / filename).exists())
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertIn("required property var game", game_card)
        self.assertIn("card.game.artwork_url", game_card)
        self.assertIn("signal collectionChanged", library_space)
        self.assertIn("signal launchRequested", library_space)

    def test_home_uses_one_fixed_content_stage_and_compact_library_object(self) -> None:
        self.assertIn("readonly property real headingCardGap: design(21)", QML)
        self.assertIn("readonly property real homeHintTopY: height - design(45)", QML)
        self.assertIn("homeContentOriginY: homeHintTopY - acceptedRecentCardHeight - headingCardGap", QML)
        self.assertIn("selectedDomainY: homeContentOriginY - activeHeadingHeight - headingCardGap", QML)
        self.assertIn("acceptedRecentCardHeight", QML)
        self.assertIn("y: root.selectedDomainY + root.domainOffset(index) * root.design(42)", QML)
        self.assertIn("function domainOffset(index)", QML)
        self.assertIn("y: root.homeContentOriginY", QML)
        self.assertNotIn("root.domainIndex * 40", QML)
        library_home = (ROOT / "ui" / "LibraryHome.qml").read_text()
        self.assertIn('text: "All Games"', library_home)
        self.assertIn("property real cardHeight", library_home)
        self.assertIn("height: cardHeight", library_home)
        self.assertIn("readonly property real libraryGameCardAspectRatio: 1 / 1.55", library_home)
        self.assertIn("width: cardHeight * libraryGameCardAspectRatio", library_home)
        self.assertIn("libraryHomeCard.width * 0.45", library_home)
        self.assertNotIn("gameCount", library_home)
        self.assertNotIn("selectedGame", library_home)

    def test_cards_preserve_portrait_artwork_and_library_density(self) -> None:
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertIn(": width * 1.5", game_card)
        self.assertIn("Image.PreserveAspectFit", game_card)
        self.assertIn("!recentFocal", game_card)
        self.assertIn("readonly property int gridColumns: 6", library_space)
        self.assertIn("readonly property real headerToGridGap: currentHeaderToGridGap / 2", library_space)
        self.assertIn("y: collectionSelectorBottomY + headerToGridGap", library_space)
        self.assertIn("(usableGridWidth - (gridColumns - 1) * gridGap) / gridColumns", library_space)
        self.assertIn("libraryCardHeight: libraryCardWidth * 1.55", library_space)
        self.assertIn("id: gridViewport", library_space)
        self.assertIn("clip: true", library_space)
        self.assertIn("y: -gridRow * gridRowStep", library_space)
        self.assertIn("visible: gridContentHeight + gameGrid.y > parent.height", library_space)
        self.assertIn("horizontalAlignment: Text.AlignHCenter", game_card)
        self.assertIn("verticalAlignment: Text.AlignVCenter", game_card)
        self.assertIn("elide: card.compact ? Text.ElideNone : Text.ElideRight", game_card)

    def test_recent_has_distinct_focal_and_compact_geometry(self) -> None:
        recent = (ROOT / "ui" / "RecentHome.qml").read_text()
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        play_shader = (ROOT / "ui" / "shaders" / "play-stacked-glass.frag").read_text()
        artwork_shader = (ROOT / "ui" / "shaders" / "card-rounded.frag").read_text()
        self.assertIn("property real focalCardHeight", recent)
        self.assertIn("x: index === selectedIndex", recent)
        self.assertIn("readonly property bool recentFocal", game_card)
        self.assertIn('text: "Last played "', game_card)
        self.assertIn('text: "A  Play"', game_card)
        self.assertIn("maximumLineCount: 2", game_card)
        self.assertIn("property real artworkRadius: recentFocal ? 18 * focalScale * uiScale : 0", game_card)
        self.assertIn("property real artworkRadius", game_card)
        self.assertIn("cornerRadius: artworkFrame.artworkRadius / Math.min(width, height)", game_card)
        self.assertIn("property int diagnosticMode: 0", game_card)
        self.assertIn("vec4(vec3(alpha), alpha)", artwork_shader)
        self.assertIn("property real artworkBorderAlpha: 0.15", game_card)
        self.assertIn("property vector2d artworkSize", game_card)
        self.assertIn("float pixelWidth = borderWidthPx / min(artworkSize.x, artworkSize.y)", artwork_shader)
        self.assertIn("float border = smoothstep", artwork_shader)
        self.assertIn('color: recentFocal ? "transparent" : "#10182b"', game_card)
        self.assertIn("sourceItem: artworkSource", game_card)
        self.assertIn("hideSource: true", game_card)
        self.assertIn("sourceItem: artworkSource\n            hideSource: true\n            visible: false", game_card)
        self.assertIn("readonly property real focalMargin", game_card)
        self.assertIn("property real focalScale", game_card)
        self.assertIn('property string presentationState: "COMPACT"', game_card)
        self.assertIn('presentationState: modelData.game_id === recentHome.selectedGameId ? "FOCUSED" : "COMPACT"', recent)
        self.assertIn("readonly property string selectedGameId", recent)
        self.assertIn('required property string modelData', library_space)
        self.assertIn('transitionState: root.libraryTransitionState', shell)
        self.assertIn('property string libraryTransitionState: "RESTING"', shell)
        self.assertIn("focalScale: 0.67", (ROOT / "ui" / "ConsoleShell.qml").read_text())
        self.assertIn("fragmentShader", game_card)
        self.assertIn("canonicalTexture", game_card)
        self.assertIn("PlayGlassSurface", game_card)
        self.assertIn("canonicalTexture: card.canonicalTexture", game_card)
        self.assertIn("playButton.mapToItem(card", game_card)
        self.assertIn("float playMask", play_shader)
        self.assertIn("u_diagnostic", play_shader)
        self.assertIn("u_diagnostic == 1", play_shader)
        self.assertIn("u_diagnostic == 2", play_shader)
        self.assertIn("result.rgb * playMask, playMask", play_shader)
        self.assertIn("readonly property real focalMargin", game_card)
        self.assertIn("x: focalMargin + artworkWidth + focalMargin", game_card)
        self.assertIn("anchors.right: parent.right", game_card)
        self.assertIn("anchors.bottom: parent.bottom", game_card)
        self.assertNotIn("card.game.provider.toUpperCase()", game_card)

    def test_orbit_backdrop_uses_qsb_and_plain_fallback(self) -> None:
        backdrop = (ROOT / "ui" / "OrbitBackdrop.qml").read_text()
        shader_builder = (ROOT / "scripts" / "build-orbit-shader.sh").read_text()
        adapter = (ROOT / "scripts" / "build-orbit-qsb.py").read_text()
        self.assertIn('fragmentShader: "shaders/orbit-wave.frag.qsb"', backdrop)
        self.assertIn('color: "#060b16"', backdrop)
        self.assertIn("ShaderEffect.Compiled", backdrop)
        self.assertIn("--qt6", shader_builder)
        self.assertIn("wave.frag", shader_builder)
        for uniform in ("u_resolution", "u_origin", "u_canvas", "u_time", "u_brightness", "u_visibility", "u_primary", "u_secondary", "u_surface", "u_error"):
            self.assertIn(uniform, adapter)
        self.assertIn('replace("gl_FragColor", "fragColor")', adapter)

    def test_canonical_identity_path_uses_shared_texture(self) -> None:
        glass = (ROOT / "ui" / "GlassSurface.qml").read_text()
        shader = (ROOT / "ui" / "shaders" / "canonical-identity.frag").read_text()
        self.assertIn("canonicalTexture", glass)
        self.assertIn("vec2 canonicalUv = scenePosition / u_canonicalSize", shader)
        self.assertNotIn("ShaderEffectSource", glass)

    def test_new_glass_material_is_separate_from_archived_experiment(self) -> None:
        glass = (ROOT / "ui" / "GlassSurface.qml").read_text()
        shader = (ROOT / "ui" / "shaders" / "canonical-snell-refraction.frag").read_text()
        self.assertIn('fragmentShader: "shaders/canonical-snell-refraction.frag.qsb"', glass)
        self.assertIn("vec3 incident = vec3(0.0, 0.0, -1.0)", shader)
        self.assertIn("refract(incident", shader)
        self.assertIn("surfaceHeight", shader)
        self.assertIn("surfaceGradient", shader)
        self.assertIn("gradient / (2.0 * stepUv)", shader)
        self.assertIn("u_diagnostic == 7", shader)
        self.assertIn("u_diagnostic == 8", shader)
        self.assertIn("u_diagnostic == 9", shader)
        self.assertIn("u_diagnostic == 10", shader)
        self.assertIn("20.0 / u_canonicalSize.x", shader)
        self.assertIn("float safeRadius = min(radius, min(halfSize.x, halfSize.y))", shader)
        self.assertIn("float transitionWidth = max(u_bevelWidthPx, 1.0)", shader)
        self.assertIn("return t * t * t * (t * (t * 6.0 - 15.0) + 10.0)", shader)
        self.assertIn("float distanceIntoBevel = transitionWidth + boundaryDistance", shader)
        self.assertIn("u_bulgeStrength", shader)
        self.assertIn("u_sceneLightStrength", shader)
        self.assertIn("u_sceneLightPixels", shader)
        self.assertIn("sceneLuminance", shader)
        self.assertIn("sceneEnergy = diffuseSample(baseUv, lightFilterRadius)", shader)
        self.assertIn("normalResponse", shader)
        self.assertIn("u_edgeLightStrength", shader)
        self.assertIn("u_edgeLightDirection", shader)
        self.assertIn("grazingResponse", shader)
        self.assertIn("edgeBand", shader)
        self.assertIn("perimeterEnvelope", shader)
        self.assertIn("(boundaryDistance + u_bevelWidthPx) / u_bevelWidthPx", shader)
        self.assertIn("float edgeBand = smootherstep(bevelCoordinate)", shader)
        self.assertIn("float bulgeShape = cos", shader)
        self.assertIn("float bulgeFade", shader)
        self.assertIn("centralBulgeHeight", shader)
        self.assertIn("centralBulgeGradient", shader)
        self.assertIn("u_diagnostic >= 11 && u_diagnostic <= 13", shader)
        self.assertIn("u_dispersionIor", shader)
        self.assertIn("rayRed", shader)
        self.assertIn("rayGreen", shader)
        self.assertIn("rayBlue", shader)
        self.assertIn("diffuseSample", shader)
        self.assertIn("u_diffusionPixels", shader)
        self.assertIn("clamp(centerUv", shader)
        self.assertIn("const float weights[5]", shader)
        self.assertIn("for (int y = 0; y < 5", shader)
        self.assertIn("u_transmission", shader)
        self.assertIn("fragColor.rgb *= clamp(u_transmission", shader)
        self.assertIn("roundedRectangleDistance", shader)
        self.assertIn("fwidth(boundaryDistance)", shader)
        self.assertIn("mix(canonicalBackdrop, fragColor, roundedMask)", shader)
        self.assertNotIn("roundedDistance", shader)
        self.assertNotIn("normalize(ray.xy)", shader)

    def test_shell_profile_routes_semantic_events_to_qt_keys(self) -> None:
        for button, key in (
            ("DPadUp", "KeyUp"),
            ("DPadDown", "KeyDown"),
            ("DPadLeft", "KeyLeft"),
            ("DPadRight", "KeyRight"),
            ("South", "KeyEnter"),
            ("East", "KeyBackspace"),
        ):
            self.assertIn(f"button: {button}", SHELL_PROFILE)
            self.assertIn(f"keyboard: {key}", SHELL_PROFILE)

    def test_launch_errors_are_not_reported_as_catalogue_failures(self) -> None:
        self.assertIn('encodeURIComponent(game.game_id)', QML)
        self.assertIn('}, "Launch failed", generation)', QML)

    def test_launch_status_is_transactional_and_catalogue_focus_is_identity_based(self) -> None:
        self.assertIn('property string launchStatus: "idle"', QML)
        self.assertIn("property int launchGeneration: 0", QML)
        self.assertIn("property string launchToken: \"\"", QML)
        self.assertIn("property int launchStateSerial: 0", QML)
        self.assertIn("property int launchStateRank: 0", QML)
        self.assertIn("function applyLaunchState(state, generation)", QML)
        self.assertIn("state.launch_token", QML)
        self.assertIn("var selectedId = visibleRecentGame ? visibleRecentGame.game_id : \"\"", QML)
        self.assertIn("selectedIndex = index", QML)
        self.assertNotIn('message = "Launch requested"', QML)
        self.assertIn("if (stateRank < launchStateRank)", QML)
        self.assertIn('state.lifecycle === "presentation_pending"', QML)
        self.assertIn('launchStatus === "launching" || launchStatus === "running"', QML)


if __name__ == "__main__":
    unittest.main()
