import unittest
from pathlib import Path


ROOT = Path(__file__).parents[1]
QML = (ROOT / "ui" / "ConsoleShell.qml").read_text()
SHELL_PROFILE = (ROOT / "config" / "inputplumber" / "profiles" / "shell.yaml").read_text()


class ConsoleUiTests(unittest.TestCase):
    def test_qml_preserves_card_to_space_shell_interaction(self) -> None:
        self.assertIn('property var domains: ["System", "Store", "Library", "Recent"]', QML)
        self.assertIn("property int selectedCategoryIndex: 3", QML)
        self.assertIn('property string space: "home"', QML)
        self.assertIn('space = "library"', QML)
        self.assertIn('space = "home"', QML)
        self.assertIn('readonly property string apiUrl:', QML)
        self.assertIn("function activate()", QML)
        self.assertIn("function moveDomain(delta)", QML)
        self.assertIn("function openSteamStore()", QML)
        self.assertIn('message = "System space is not implemented"', QML)
        self.assertIn('function openGameOptions(game)', QML)
        self.assertIn('event.key === Qt.Key_X', QML)
        self.assertIn('action: "options"', QML)
        self.assertIn('GameOptions {', QML)
        self.assertIn('space === "library" && libraryFocus === "games"', QML)
        self.assertIn('space === "home" && selectedCategoryIndex === 3', QML)
        self.assertIn('if (gameOptionsView === "menu")', QML)
        self.assertIn("Math.max(0, Math.min(domains.length - 1", QML)
        self.assertIn("Math.max(0, Math.min(recentGames.length - 1", QML)
        self.assertNotIn("% domains.length", QML)
        self.assertNotIn("% recentGames.length", QML)
        self.assertNotIn("Behavior on opacity", QML)
        self.assertNotIn("Behavior on scale", QML)
        recent = (ROOT / "ui" / "RecentHome.qml").read_text()
        self.assertIn("toRelativeIndex: index - recentHome.selectedIndex", recent)
        self.assertIn("presentationStartVisible[index]", recent)
        self.assertIn("capturePresentation()", recent)
        self.assertIn("suppressTransitionCompletion", recent)
        self.assertIn("transitionAnimation.stop()", recent)
        self.assertIn("transitionAnimation.start()", recent)
        self.assertIn("compactCardWidth + railGap", recent)
        self.assertNotIn("edgeViewportWidth", recent)
        self.assertNotIn("edgePeek", recent)
        self.assertIn("x: -root.homeContentRailX", QML)
        self.assertIn("titleRailY", QML)
        self.assertIn("titleRailTargetY", QML)
        self.assertIn("titleRailActiveGap", QML)
        self.assertIn("titleRailLayoutY(index, activeIndex)", QML)
        self.assertIn("visible: true", QML)
        self.assertIn("anchors.rightMargin: root.design(76)", QML)
        self.assertIn("homeBottomBandCenterY: height - design(36)", QML)
        self.assertIn("homeCategoryRailX: design(52)", QML)
        self.assertIn('homeCategoryFontSize: typography.size("display", 48)', QML)
        self.assertIn("homeCategoryGap: design(25)", QML)
        self.assertIn("homeCategoryPitch: homeCategoryFontSize + homeCategoryGap", QML)
        self.assertNotIn('text: "HOME"', QML)
        self.assertIn("homeFocalCardHeight", QML)
        self.assertIn("homeFocalCardWidth", QML)
        self.assertIn("homeCompactCardWidth", QML)
        self.assertIn("homeInterCardGap: design(24)", QML)
        self.assertIn("homeHeadingCardClearance: design(12)", QML)
        self.assertIn("homeCompositionOffsetY: -design(36)", QML)
        self.assertIn("opacity: libraryHome.contentOpacity", (ROOT / "ui" / "LibraryHome.qml").read_text())
        self.assertIn("property bool libraryHandoffPending: false", QML)
        self.assertIn("handoffTimer.restart()", QML)
        self.assertIn("NavigationCard", (ROOT / "ui" / "LibraryHome.qml").read_text())
        self.assertIn('request("/?scope=recent"', QML)
        self.assertIn('readonly property string libraryScope:', QML)
        self.assertNotIn("/dev/input", QML)
        self.assertNotIn("Social", QML)

    def test_reset_mudos_uses_the_shared_session_boundary(self) -> None:
        guide = (ROOT / "ui" / "MudosGuide.qml").read_text()
        system_space = (ROOT / "ui" / "SystemSpace.qml").read_text()
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        native_guide = (ROOT / "native" / "mudos-guide.cpp").read_text()
        self.assertIn('"Reset Mudos"', guide)
        self.assertIn('"Switch to Compatibility Mode"', guide)
        self.assertIn('"Switch to Gamepad Mode"', guide)
        self.assertIn('call("SetInputMode"', native_guide)
        self.assertIn('state.value("lifecycle").toString() != QStringLiteral("shell")', native_guide)
        self.assertIn('key === "lulu.reset"', system_space + QML)
        self.assertIn('request("/reset", "POST"', QML)
        self.assertIn("call_reset_mudos", bridge)
        self.assertIn('path == "/reset"', bridge)

    def test_shell_guide_is_limited_and_confirms_power_actions_natively(self) -> None:
        guide = (ROOT / "ui" / "MudosGuide.qml").read_text()
        native_guide = (ROOT / "native" / "mudos-guide.cpp").read_text()
        native_shell = (ROOT / "native" / "lulu-shell.cpp").read_text()
        self.assertIn('return ["Restart Mudos", "Reboot System", "Shut Down System"]', guide)
        self.assertIn('state.value("lifecycle").toString() != QStringLiteral("game")', native_guide)
        self.assertIn('viewModel_->value("confirmationPending").toBool()', native_guide)
        self.assertIn('logind.call(method, false)', native_guide)
        self.assertIn('QStringLiteral("Reboot")', native_guide)
        self.assertIn('QStringLiteral("PowerOff")', native_guide)
        self.assertNotIn('"Quit Application"', guide)
        self.assertNotIn('systemctl', guide)
        self.assertNotIn('focusedWindow_ == window_->winId()', native_shell)

    def test_retroarch_provider_menu_fallback_is_native_and_platform_scoped(self) -> None:
        native_guide = (ROOT / "native" / "mudos-guide.cpp").read_text()
        self.assertIn('primaryId.startsWith(QStringLiteral("local:nes:"))', native_guide)
        self.assertIn('primaryId.startsWith(QStringLiteral("local:genesis:"))', native_guide)
        self.assertIn('QStringLiteral("/usr/bin/retroarch --command MENU_TOGGLE")', native_guide)
        self.assertNotIn('primaryId.startsWith(QStringLiteral("local:ps2:"))', native_guide)

    def test_extracted_ui_primitives_preserve_real_game_card_data(self) -> None:
        for filename in ("GameCard.qml", "RecentHome.qml", "LibraryHome.qml", "LibrarySpace.qml", "PlaceholderHome.qml"):
            self.assertTrue((ROOT / "ui" / filename).exists())
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertIn("property var game: null", game_card)
        self.assertIn("card.game.artwork_url", game_card)
        self.assertIn("signal collectionChanged", library_space)
        self.assertIn("signal launchRequested", library_space)

    def test_typography_uses_central_semantic_families(self) -> None:
        typography = (ROOT / "ui" / "Typography.qml").read_text()
        self.assertIn('displayFamily: "Zalando Sans Condensed Black"', typography)
        self.assertIn("displayWeight: Font.Black", typography)
        self.assertIn('interfaceFamily: "JetBrains Mono"', typography)
        self.assertIn("function size(role, value)", typography)
        for filename in ("ConsoleShell.qml", "GameCard.qml", "LibraryHome.qml", "LibrarySpace.qml", "PlaceholderHome.qml", "RecentHome.qml"):
            self.assertIn("typography", (ROOT / "ui" / filename).read_text())

    def test_ui_palette_is_semantic_and_centralized(self) -> None:
        palette = (ROOT / "ui" / "LuluPalette.qml").read_text()
        for role in ("primaryText", "secondaryText", "mutedText", "selectedText", "accent",
                     "focusIndicator", "warning", "glassTint", "glassBorder", "backdrop"):
            self.assertIn("property color " + role, palette)
        for filename in ("ConsoleShell.qml", "GameCard.qml", "RecentHome.qml", "LibraryHome.qml", "LibrarySpace.qml", "PlaceholderHome.qml"):
            component = (ROOT / "ui" / filename).read_text()
            self.assertIn("luluPalette", component)
            self.assertNotRegex(component, r'(?m)^\s*(?:border\.)?color:\s*"#')

    def test_system_settings_is_controller_first_and_backend_driven(self) -> None:
        system_home = (ROOT / "ui" / "SystemHome.qml").read_text()
        system_space = (ROOT / "ui" / "SystemSpace.qml").read_text()
        self.assertIn('property var systemCategories:', QML)
        self.assertIn('property var systemSettings:', QML)
        self.assertIn('systemCategoryIndex = Math.max(0, systemCategoryIndex - 1)', QML)
        self.assertIn('systemCategoryIndex = Math.min(systemCategories.length - 1, systemCategoryIndex + 1)', QML)
        self.assertIn('request("/settings?category="', QML)
        self.assertIn('signal openRequested(int index)', system_home)
        self.assertIn('PageUp', QML)
        self.assertIn('PageDown', QML)
        self.assertIn('modelData.label', system_space)

    def test_navigation_cards_share_the_all_games_surface(self) -> None:
        navigation_card = (ROOT / "ui" / "NavigationCard.qml").read_text()
        navigation_surface = (ROOT / "ui" / "NavigationCardSurface.qml").read_text()
        store = (ROOT / "ui" / "StoreHome.qml").read_text()
        system = (ROOT / "ui" / "SystemHome.qml").read_text()
        library_surface = (ROOT / "ui" / "LibrarySpatialSurface.qml").read_text()
        self.assertIn("NavigationCardSurface {", navigation_card)
        self.assertIn("transmission: 1", navigation_surface)
        self.assertIn("bulgeStrength: 100", navigation_surface)
        self.assertIn("NavigationCard {", store)
        self.assertIn("NavigationCard {", system)
        self.assertIn("NavigationCardSurface {", library_surface)
        self.assertIn("selectionProgress", system)
        self.assertIn("function railX(relativeIndex)", system)
        self.assertIn("presentationStartX", system)
        self.assertIn("captureSelection()", system)
        self.assertIn("onActivated: root.openRequested(index)", system)
        self.assertIn("property url artworkSource", navigation_card)
        self.assertIn('artworkSource: Qt.resolvedUrl("artwork/store.svg")', store)
        self.assertIn("function platformArtwork(scope)", (ROOT / "ui" / "LibraryHome.qml").read_text())
        self.assertIn("function categoryArtwork(category)", system)
        self.assertNotIn("border.width", (ROOT / "ui" / "NavigationCard.qml").read_text())
        self.assertNotIn("anchors.margins: -8", (ROOT / "ui" / "NavigationCard.qml").read_text())
        self.assertIn("onOpenRequested: root.openSystemCategory(index)", QML)
        self.assertIn("function openSystemCategory(index)", QML)
        self.assertNotIn("root.activate()\n            }", QML)

    def test_non_game_portrait_artwork_assets_are_replaceable(self) -> None:
        artwork = ROOT / "ui" / "artwork"
        expected = {
            "platform-all.svg", "platform-steam.svg", "store.svg",
            "system-display.svg", "system-audio.svg", "system-network.svg",
            "system-bluetooth.svg", "system-controllers.svg", "system-storage.svg",
            "system-system.svg", "system-lulu.svg",
        }
        self.assertEqual({path.name for path in artwork.glob("*.svg")}, expected)
        for path in artwork.glob("*.svg"):
            self.assertGreater(path.stat().st_size, 0)

    def test_home_uses_one_fixed_content_stage_and_compact_library_object(self) -> None:
        self.assertIn("readonly property real headingCardGap: design(21)", QML)
        self.assertIn("readonly property real homeHintTopY: height - design(45)", QML)
        self.assertIn("homeContentOriginY: homeHintTopY - acceptedRecentCardHeight - headingCardGap", QML)
        self.assertIn("selectedDomainY: homeActiveContentOriginY - homeHeadingCardClearance", QML)
        self.assertIn("acceptedRecentCardHeight", QML)
        self.assertIn("y: root.titleRailChildY(index)", QML)
        self.assertIn("function domainOffset(index)", QML)
        self.assertIn("y: root.homeActiveContentOriginY", QML)
        self.assertIn("root.homeCategoryTransitioning", QML)
        self.assertIn("homeCategoryTarget === 2", QML)
        self.assertIn("homeCategoryFrom === 2", QML)
        self.assertIn("homeCategoryTarget === 3", QML)
        self.assertIn("homeCategoryRevealHeight(index)", QML)
        self.assertIn("desiredCategoryIndex", QML)
        self.assertIn("function startNextHomeCategoryHop(chained)", QML)
        self.assertIn("homeCategoryHopDuration", QML)
        self.assertIn("homeCategoryHopDuration = chained ? 100 : 250", QML)
        self.assertIn("duration: root.homeCategoryHopDuration", QML)
        self.assertIn("if (homeCategoryAnimation.running)", QML)
        self.assertIn("id: libraryReveal", QML)
        self.assertIn('surfaceVisible: root.space === "library" || root.libraryTransitioning', QML)
        self.assertIn("x: -root.homeContentRailX", QML)
        self.assertIn("id: homeCardViewport", QML)
        self.assertIn("id: systemReveal\n                    x: -root.homeContentRailX", QML)
        self.assertIn("id: systemHomeRail\n                        x: root.homeContentRailX", QML)
        self.assertIn("id: homeCardViewport\n                x: 0", QML)
        self.assertIn("id: homeContent\n                x: root.homeContentRailX", QML)
        self.assertIn("height: root.homeBottomBandCenterY - root.homeActiveContentOriginY", QML)
        self.assertIn("clip: true", QML)
        self.assertIn("opacity: 1", QML)
        self.assertNotIn("homeCategoryOpacityProgress", QML)
        self.assertNotIn("homeCategoryOpacityAnimation", QML)
        self.assertNotIn("root.domainIndex * 40", QML)
        library_home = (ROOT / "ui" / "LibraryHome.qml").read_text()
        self.assertIn('model: ["All Games", "Steam"]', library_home)
        self.assertIn("NavigationCard", library_home)
        self.assertIn("presentationStartX", library_home)
        self.assertIn("function railX(relativeIndex)", library_home)
        self.assertIn("targetX: libraryHome.railX(index - libraryHome.selectedIndex)", library_home)
        self.assertIn("moveLibraryLanding", QML)
        self.assertIn("selectedIndex: root.collectionIndex", QML)
        self.assertIn("property real cardHeight", library_home)
        self.assertIn("height: libraryHome.cardHeight", library_home)
        self.assertIn("width: libraryHome.compactCardWidth", library_home)
        self.assertIn('artworkSource: libraryHome.platformArtwork(modelData.scope)', library_home)
        self.assertIn("canonicalCoordinateRoot", library_home)
        self.assertIn("interval: 16", library_home)
        self.assertIn("repeat: true", library_home)
        self.assertNotIn("gameCount", library_home)
        self.assertNotIn("selectedGame", library_home)

    def test_cards_preserve_portrait_artwork_and_library_density(self) -> None:
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        self.assertIn("visible: card.focalChromeOpacity > 0", game_card)
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertIn("compactArtworkWidth * 1.5", game_card)
        self.assertIn("compactArtworkWidth", game_card)
        self.assertIn("compactArtworkHeight", game_card)
        self.assertIn("Image.PreserveAspectFit", game_card)
        self.assertIn("presentationProgress < 1", game_card)
        self.assertIn("readonly property int gridColumns: 7", library_space)
        self.assertIn("verticalCardWidth", library_space)
        self.assertIn("gridLeftInset", library_space)
        self.assertIn("gridTop - gridTopInset", library_space)
        self.assertIn("gridRegionHeight + gridTopInset + gridBottomInset", library_space)
        self.assertIn("2 * (fullscreenPanelCardSelectionScale - 1.0)", library_space)
        self.assertIn("Math.min(horizontalCardWidth, verticalCardWidth)", library_space)
        self.assertIn("fullscreenPanelBevelWidth: 6 * uiScale", library_space)
        self.assertIn("gridHorizontalGrowth", library_space)
        self.assertIn("gridVerticalGrowth", library_space)
        self.assertIn("(fullscreenPanelCardSelectionScale - 1.0) * libraryCardHeight", library_space)
        self.assertIn("fullscreenPanelBorderWidth: 0", library_space)
        self.assertIn("fullscreenPanelTransmission: 1", library_space)
        self.assertNotIn("border.color: luluPalette.libraryHighlight", library_space)
        self.assertIn("scale: focused ? librarySpace.fullscreenPanelCardSelectionScale : 1", library_space)
        self.assertIn("z: focused ? 2 : 1", library_space)
        self.assertIn("unfocusedBrightness: 0.6", library_space)
        self.assertIn("focusBrightness: focused ? 1 : librarySpace.unfocusedBrightness", library_space)
        self.assertIn("stackedCardBevelWidth: 3 * librarySpace.uiScale", library_space)
        self.assertIn("stackedCardBulgeStrength: 0", library_space)
        self.assertIn("stackedCardRefractionPixels: 0", library_space)
        self.assertIn("stackedCardDispersionIor: 0", library_space)
        self.assertIn("stackedPlayRefractionPixels: 8 * librarySpace.uiScale", library_space)
        self.assertIn("stackedPlayDispersionIor: 0", library_space)
        self.assertIn("stackedPlayBulgeStrength: 0", library_space)
        self.assertIn("stackedPlayBevelWidth: 3 * librarySpace.uiScale", library_space)
        self.assertIn("bevelHeight", (ROOT / "ui" / "shaders" / "play-stacked-glass.frag").read_text())
        self.assertIn("cardSurfaceGradient", (ROOT / "ui" / "shaders" / "play-stacked-glass.frag").read_text())
        self.assertIn("property real focusBrightness: 1", game_card)
        self.assertIn("readonly property real headerToGridGap: currentHeaderToGridGap / 2", library_space)
        self.assertIn("gridTop: collectionSelectorBottomY + headerToGridGap", library_space)
        self.assertIn("horizontalCardWidth", library_space)
        self.assertIn("libraryCardHeight: libraryCardWidth * 1.55", library_space)
        self.assertIn("id: gridViewport", library_space)
        self.assertIn("clip: true", library_space)
        self.assertIn("gridTopInset - firstVisibleRow * gridRowStep", library_space)
        self.assertNotIn("scrollFadeStart", library_space)
        self.assertNotIn("scrollFadeEnd", library_space)
        self.assertIn("horizontalAlignment: Text.AlignHCenter", game_card)
        self.assertIn("verticalAlignment: Text.AlignVCenter", game_card)
        self.assertIn("elide: Text.ElideRight", game_card)

    def test_recent_has_distinct_focal_and_compact_geometry(self) -> None:
        recent = (ROOT / "ui" / "RecentHome.qml").read_text()
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        play_shader = (ROOT / "ui" / "shaders" / "play-stacked-glass.frag").read_text()
        artwork_shader = (ROOT / "ui" / "shaders" / "card-rounded.frag").read_text()
        self.assertIn("property real focalCardHeight", recent)
        self.assertIn("x: startX + (recentHome.railX(toRelativeIndex) - startX) * railProgress", recent)
        self.assertIn("focalChromeOpacity", recent)
        self.assertIn("startChrome", recent)
        self.assertIn("startCompactTitle", recent)
        self.assertIn('console.log("RECENT_RETARGET", "capture"', recent)
        self.assertIn('console.log("RECENT_RETARGET", "target"', recent)
        self.assertIn("duration: 500", recent)
        self.assertIn("easing.type: Easing.OutQuint", recent)
        self.assertIn('property: "transitionFadeProgress"', recent)
        self.assertIn("z: 2", game_card)
        self.assertIn("property real compactCardWidth", recent)
        self.assertIn("height: focalCardHeight", recent)
        self.assertIn("compactCardWidth + railGap", recent)
        self.assertIn("readonly property bool recentFocal", game_card)
        self.assertIn("property real compactTitleOpacity", game_card)
        self.assertIn("card.compactEndpointWidth > 0", game_card)
        self.assertIn('"Last played " + Qt.formatDateTime', game_card)
        self.assertIn('text: "A  Play"', game_card)
        self.assertIn("maximumLineCount: 2", game_card)
        self.assertIn("wrapMode: Text.WordWrap", game_card)
        self.assertIn("property real artworkRadius: card.mix", game_card)
        self.assertIn("property real artworkRadius", game_card)
        self.assertIn("cornerRadius: artworkFrame.artworkRadius / Math.min(width, height)", game_card)
        self.assertIn("property int diagnosticMode: 0", game_card)
        self.assertIn("vec4(vec3(alpha), alpha)", artwork_shader)
        self.assertIn("property real artworkBorderAlpha: 0.15", game_card)
        self.assertIn("property vector2d artworkSize", game_card)
        self.assertIn("float pixelWidth = borderWidthPx / min(artworkSize.x, artworkSize.y)", artwork_shader)
        self.assertIn("float border = smoothstep", artwork_shader)
        self.assertIn("luluPalette.artworkSurface", game_card)
        self.assertIn('card.compact ? 14 * 0.8 : 16', game_card)
        self.assertIn("sourceItem: artworkSource", game_card)
        self.assertIn("hideSource: true", game_card)
        self.assertIn("sourceItem: artworkSource\n            hideSource: true\n            visible: false", game_card)
        self.assertIn("readonly property real focalMargin", game_card)
        self.assertIn("property real focalScale", game_card)
        self.assertIn('property string presentationState: "COMPACT"', game_card)
        self.assertIn('presentationState: modelData.game_id === recentHome.selectedGameId ? "FOCUSED" : "COMPACT"', recent)
        self.assertIn("readonly property string selectedGameId", recent)
        self.assertIn('required property string modelData', library_space)
        self.assertIn('transitionState: root.libraryTransitionState', shell)
        self.assertIn('property string libraryTransitionState: "RESTING"', shell)
        self.assertIn("focalScale: 0.67", (ROOT / "ui" / "ConsoleShell.qml").read_text())
        self.assertIn("fragmentShader", game_card)
        self.assertIn("canonicalTexture", game_card)
        self.assertIn("PlayGlassSurface", game_card)
        self.assertIn("canonicalTexture: card.canonicalTexture", game_card)
        self.assertIn('useExplicitSceneGeometry: card.presentationState === "COMPACT"', game_card)
        self.assertIn("canonicalCoordinateRoot", game_card)
        self.assertIn("card.mapToItem(canonicalCoordinateRoot, 0, 0)", game_card)
        self.assertIn("actualGlassSurface.mapToItem", game_card)
        self.assertIn("liveSceneCoordinates: true", recent)
        self.assertIn("opticsStage: blend > 0 ? 7 : -1", recent)
        self.assertIn("layoutDependency = card.x + card.y + card.width + card.height", game_card)
        self.assertIn("property bool useExplicitSceneGeometry", (ROOT / "ui" / "GlassSurface.qml").read_text())
        self.assertIn("canonical-identity.frag.qsb", (ROOT / "ui" / "GlassSurface.qml").read_text())
        self.assertIn("playButton.mapToItem(card", game_card)
        self.assertIn("float playMask", play_shader)
        self.assertIn("u_diagnostic", play_shader)
        self.assertIn("u_diagnostic == 1", play_shader)
        self.assertIn("u_diagnostic == 2", play_shader)
        self.assertIn("result.rgb * playMask, playMask", play_shader)
        self.assertIn("readonly property real focalMargin", game_card)
        self.assertIn("focalMargin + artworkWidth + focalMargin", game_card)
        self.assertIn("anchors.right: parent.right", game_card)
        self.assertIn("anchors.bottom: parent.bottom", game_card)
        self.assertNotIn("card.game.provider.toUpperCase()", game_card)

    def test_orbit_backdrop_uses_qsb_and_plain_fallback(self) -> None:
        backdrop = (ROOT / "ui" / "OrbitBackdrop.qml").read_text()
        shader_builder = (ROOT / "scripts" / "build-orbit-shader.sh").read_text()
        adapter = (ROOT / "scripts" / "build-orbit-qsb.py").read_text()
        self.assertIn('fragmentShader: "shaders/orbit-wave.frag.qsb"', backdrop)
        self.assertIn('color: "#060b16"', backdrop)
        self.assertIn("ShaderEffect.Compiled", backdrop)
        self.assertIn("--qt6", shader_builder)
        self.assertIn("wave.frag", shader_builder)
        for uniform in ("u_resolution", "u_origin", "u_canvas", "u_time", "u_brightness", "u_visibility", "u_primary", "u_secondary", "u_surface", "u_error"):
            self.assertIn(uniform, adapter)
        self.assertIn('replace("gl_FragColor", "fragColor")', adapter)

    def test_canonical_identity_path_uses_shared_texture(self) -> None:
        glass = (ROOT / "ui" / "GlassSurface.qml").read_text()
        shader = (ROOT / "ui" / "shaders" / "canonical-identity.frag").read_text()
        self.assertIn("canonicalTexture", glass)
        self.assertIn("vec2 canonicalUv = scenePosition / u_canonicalSize", shader)
        self.assertNotIn("ShaderEffectSource", glass)

    def test_new_glass_material_is_separate_from_archived_experiment(self) -> None:
        glass = (ROOT / "ui" / "GlassSurface.qml").read_text()
        shader = (ROOT / "ui" / "shaders" / "canonical-snell-refraction.frag").read_text()
        self.assertIn('"shaders/canonical-snell-refraction.frag.qsb"', glass)
        self.assertIn("vec3 incident = vec3(0.0, 0.0, -1.0)", shader)
        self.assertIn("refract(incident", shader)
        self.assertIn("surfaceHeight", shader)
        self.assertIn("surfaceGradient", shader)
        self.assertIn("gradient / (2.0 * stepUv)", shader)
        self.assertIn("u_diagnostic == 7", shader)
        self.assertIn("u_diagnostic == 8", shader)
        self.assertIn("u_diagnostic == 9", shader)
        self.assertIn("u_diagnostic == 10", shader)
        self.assertIn("20.0 / u_canonicalSize.x", shader)
        self.assertIn("float safeRadius = min(radius, min(halfSize.x, halfSize.y))", shader)
        self.assertIn("float transitionWidth = max(u_bevelWidthPx, 1.0)", shader)
        self.assertIn("return t * t * t * (t * (t * 6.0 - 15.0) + 10.0)", shader)
        self.assertIn("float distanceIntoBevel = transitionWidth + boundaryDistance", shader)
        self.assertIn("u_bulgeStrength", shader)
        self.assertIn("u_sceneLightStrength", shader)
        self.assertIn("u_sceneLightPixels", shader)
        self.assertIn("sceneLuminance", shader)
        self.assertIn("sceneEnergy = diffuseSample(baseUv, lightFilterRadius)", shader)
        self.assertIn("normalResponse", shader)
        self.assertIn("u_edgeLightStrength", shader)
        self.assertIn("u_edgeLightDirection", shader)
        self.assertIn("grazingResponse", shader)
        self.assertIn("edgeBand", shader)
        self.assertIn("perimeterEnvelope", shader)
        self.assertIn("(boundaryDistance + u_bevelWidthPx) / u_bevelWidthPx", shader)
        self.assertIn("float edgeBand = smootherstep(bevelCoordinate)", shader)
        self.assertIn("float bulgeShape = cos", shader)
        self.assertIn("float bulgeFade", shader)
        self.assertIn("centralBulgeHeight", shader)
        self.assertIn("centralBulgeGradient", shader)
        self.assertIn("u_diagnostic >= 11 && u_diagnostic <= 13", shader)
        self.assertIn("u_dispersionIor", shader)
        self.assertIn("rayRed", shader)
        self.assertIn("rayGreen", shader)
        self.assertIn("rayBlue", shader)
        self.assertIn("diffuseSample", shader)
        self.assertIn("u_diffusionPixels", shader)
        self.assertIn("clamp(centerUv", shader)
        self.assertIn("const float weights[5]", shader)
        self.assertIn("for (int y = 0; y < 5", shader)
        self.assertIn("u_transmission", shader)
        self.assertIn("fragColor.rgb *= clamp(u_transmission", shader)
        self.assertIn("roundedRectangleDistance", shader)
        self.assertIn("fwidth(boundaryDistance)", shader)
        self.assertIn("mix(canonicalBackdrop, fragColor, roundedMask)", shader)
        self.assertNotIn("roundedDistance", shader)
        self.assertNotIn("normalize(ray.xy)", shader)

    def test_controller_x_routes_to_shared_game_options_action(self) -> None:
        native_shell = (ROOT / "native" / "lulu-shell.cpp").read_text()
        self.assertIn('{SDL_GAMEPAD_BUTTON_WEST, "options"}', native_shell)
        self.assertNotIn('{SDL_GAMEPAD_BUTTON_NORTH, "options"}', native_shell)
        self.assertIn('{"options", "openSelectedGameOptions"}', native_shell)
        self.assertIn("function openSelectedGameOptions()", QML)
        self.assertIn("openGameOptions(selectedGameForOptions)", QML)

    def test_game_options_owns_confirm_and_ignores_reopen(self) -> None:
        native_shell = (ROOT / "native" / "lulu-shell.cpp").read_text()
        self.assertIn('{SDL_GAMEPAD_BUTTON_SOUTH, "confirm"}', native_shell)
        self.assertIn("if (gameOptionsOpen) {\n            activateGameOptions()", QML)
        self.assertIn("if (gameOptionsOpen)\n            return\n        if (selectedGameForOptions)", QML)
        self.assertIn('if (gameOptionsOpen) {\n            if (gameOptionsView === "menu")', QML)
        self.assertIn('closeGameOptions()\n            else', QML)

    def test_shell_profile_routes_semantic_events_to_qt_keys(self) -> None:
        for button, key in (
            ("DPadUp", "KeyUp"),
            ("DPadDown", "KeyDown"),
            ("DPadLeft", "KeyLeft"),
            ("DPadRight", "KeyRight"),
            ("South", "KeyEnter"),
            ("East", "KeyBackspace"),
            ("LeftBumper", "KeyPageUp"),
            ("RightBumper", "KeyPageDown"),
        ):
            self.assertIn(f"button: {button}", SHELL_PROFILE)
            self.assertIn(f"keyboard: {key}", SHELL_PROFILE)
        self.assertIn("button: North", SHELL_PROFILE)
        self.assertIn("keyboard: KeyX", SHELL_PROFILE)

    def test_game_options_preserves_contextual_two_level_structure(self) -> None:
        options = (ROOT / "ui" / "GameOptions.qml").read_text()
        for entry in ("Change Match", "Edit Metadata", "Edit Title", "Clear Title Override"):
            self.assertIn(entry, options)
        self.assertIn('"Remove Image"', options)
        self.assertIn('"Restore Image"', options)
        self.assertIn("metadataMutation", QML)
        self.assertIn("/metadata/search?game_id=", QML)
        self.assertIn("function back()", QML)

    def test_library_navigation_separates_grid_and_collection_controls(self) -> None:
        shell = (ROOT / "ui" / "ConsoleShell.qml").read_text()
        self.assertIn("function moveLibraryVertical(delta)", shell)
        self.assertIn("var column = libraryIndex % 7", shell)
        self.assertIn("var target = row * 7 + column", shell)
        self.assertIn("moveLibraryCollection(-1)", shell)
        self.assertIn("moveLibraryCollection(1)", shell)
        self.assertIn('action: "navigation"', shell)
        self.assertIn('action: "previousCollection"', shell)
        self.assertIn('action: "nextCollection"', shell)
        self.assertIn('label: root.selectedCategoryIndex === 3 ? "Navigate / Games"', shell)
        self.assertIn('property bool libraryTransitioning: false', shell)
        self.assertIn('property: "libraryTransitionProgress"', shell)
        self.assertIn('duration: 500', shell)
        self.assertIn('easing.type: Easing.OutQuint', shell)
        self.assertIn('LibrarySpatialSurface {', shell)
        self.assertIn('homeX: root.homeContentRailX', shell)
        self.assertIn('fullscreenWidth: root.width - 152 * root.uiScale', shell)
        spatial_surface = (ROOT / "ui" / "LibrarySpatialSurface.qml").read_text()
        self.assertNotIn("z: 1", spatial_surface)
        self.assertIn('contentOpacity: root.libraryContentOpacity', shell)
        library_space = (ROOT / "ui" / "LibrarySpace.qml").read_text()
        self.assertNotIn("GlassSurface {", library_space)
        library_home = (ROOT / "ui" / "LibraryHome.qml").read_text()
        self.assertIn("NavigationCard", library_home)
        game_card = (ROOT / "ui" / "GameCard.qml").read_text()
        self.assertIn("card.stackedGlass || card.librarySurfaceMaterial", game_card)
        self.assertIn("card.librarySurfaceMaterial ? 0", game_card)
        self.assertIn('action: "confirm"', shell)
        self.assertIn("property int libraryFirstVisibleRow: 0", shell)
        self.assertIn("if (row >= libraryFirstVisibleRow + 2)", shell)
        self.assertIn("firstVisibleRow: root.libraryFirstVisibleRow", shell)

    def test_launch_errors_are_not_reported_as_catalogue_failures(self) -> None:
        self.assertIn('encodeURIComponent(game.game_id)', QML)
        self.assertIn('}, "Launch failed", generation)', QML)

    def test_launch_status_is_transactional_and_catalogue_focus_is_identity_based(self) -> None:
        self.assertIn('property string launchStatus: "idle"', QML)
        self.assertIn("property int launchGeneration: 0", QML)
        self.assertIn("property string launchToken: \"\"", QML)
        self.assertIn("property int launchStateSerial: 0", QML)
        self.assertIn("property int launchStateRank: 0", QML)
        self.assertIn("function applyLaunchState(state, generation)", QML)
        self.assertIn("state.launch_token", QML)
        self.assertIn("var selectedId = visibleRecentGame ? visibleRecentGame.game_id : \"\"", QML)
        self.assertIn("selectedIndex = index", QML)
        self.assertNotIn('message = "Launch requested"', QML)
        self.assertIn("if (stateRank < launchStateRank)", QML)
        self.assertIn('state.lifecycle === "presentation_pending"', QML)
        self.assertNotIn('launchStatus === "launching" || launchStatus === "running"', QML)
        self.assertIn("anchors.fill: parent", QML)
        self.assertIn("launchOverlayRetired = true", QML)
        self.assertIn("visible: root.launchOverlayVisible && !root.launchOverlayRetired", QML)
        self.assertIn("launchToken = data.token", QML)

        self.assertIn("refreshLaunchLog(root.launchGeneration)", QML)
        self.assertLess(QML.index("launchToken = data.token"), QML.index("            refreshLaunchState(generation)"))
        self.assertLess(QML.index("retireLaunchOverlay(generation)"), QML.index("function refreshLaunchLog(generation)"))
        self.assertIn('request("/cancel", "POST"', QML)
        self.assertIn('value === "back"', QML)
        self.assertIn('launchTitle = "Steam Store"', QML)
        bridge = (ROOT / "scripts" / "console-ui-bridge.py").read_text()
        self.assertIn('self.launch_logs.start("steam-store")', bridge)


    def test_steam_overlay_has_game_presentation_shell_return_failsafe(self) -> None:
        self.assertIn("property bool shellWasLeft: false", QML)
        self.assertIn("function finishLaunchOnShellReturn()", QML)
        self.assertIn("root.shellWasLeft = true", QML)
        self.assertIn("root.shellWasLeft = true", QML)
        self.assertIn("if (root.shellWasLeft && root.gamePresentationObserved)", QML)
        self.assertIn("launchLogTimer.stop()", QML)
        self.assertIn("launchLogLines = []", QML)
        self.assertIn("launchGeneration++", QML)
        self.assertIn('root.launchGameId.indexOf("steam:") === 0', QML)

    def test_ui_audio_engine_has_semantic_voices_and_safety_rules(self) -> None:
        engine = (ROOT / "ui" / "UiAudioEngine.qml").read_text()
        for semantic in ("navigate", "confirm", "back", "error"):
            self.assertIn(f'{semantic}Source: "sounds/ui-{semantic}.wav"', engine)
            self.assertIn(f'id: {semantic}VoiceComponent', engine)
        self.assertIn("function play(semantic)", engine)
        self.assertIn("function voiceFor(semantic)", engine)
        self.assertIn("debounceInterval: 55", engine)
        self.assertIn("maxVoices: 3", engine)
        self.assertIn("voice.status !== SoundEffect.Ready", engine)
        self.assertIn("activeVoiceCount() >= maxVoices", engine)
        self.assertIn("voice.stop()", engine)
        self.assertIn("function stopAll()", engine)
        self.assertIn("function loaderFor(semantic)", engine)
        self.assertIn("property string pendingSemantic", engine)
        self.assertIn("onLoaded: root.tryPlayPending()", engine)
        self.assertIn('source: "UiAudioEngine.qml"', QML)
        self.assertIn("active: false", QML)
        self.assertNotIn("onValueChanged", engine)

    def test_ui_audio_assets_are_canonical_and_replaceable(self) -> None:
        manifest = (ROOT / "ui" / "sounds" / "README.md").read_text()
        for filename in ("ui-navigate.wav", "ui-confirm.wav", "ui-back.wav", "ui-error.wav"):
            self.assertIn(f"`{filename}`", manifest)
        self.assertIn("does not\nrequire a", manifest)

if __name__ == "__main__":
    unittest.main()
