id = "steam"
name = "Steam"
[capabilities]
launch = true
library = true
[platforms]
supported = ["pc"]
[config]
strategy = "redirected"
directory = "config"
[launch.standalone]
command = "/usr/bin/steam steam://open/main"
controller_mode = "compat"
window_class = "steam"
[launch.game]
command = "/usr/bin/steam"
